### ISSUE TITLE
Broken documentation page (Model-definition-JSON-file)

### ISSUE THREAD

**Issue by ismirnov-ekoniva** [loopbackio/loopback.io#1003]
## URL of the page 

Github: https://github.com/strongloop/loopback.io/blob/gh-pages/pages/en/lb3/Model-definition-JSON-file.md
Site: https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html

## Nature of the issue 

All documentation content after "Data mapping properties" section is not displayed in documentation site (but persists in Github)

## Expected behavior

Github page content is equal to documetation on the site.

## Actual behavior

More then half of the page is missing

## Suggested resolution

Fix the markdown on the page, then check and fix your parser to prevent silent data corruption like this one.

**Comment by dhmlau** [comment]
@ismirnov-ekoniva, thanks for reporting it. Looking at the source on GH, looks like the table  didn't get render properly. Are you interested in submitting a PR? Thanks.

**Comment by ismirnov-ekoniva** [comment]
@dhmlau fixed non-closed div, but I cannot test it. Can you help me with this? I am also don't know how (and why I should) sign-off my commit, so pre-commit checks prevent my PR to be approved.
Is there any way to do something with my PR? People still cannot see 80% of most important documentation page of this framework (seriously, model definition is a Rosetta Stone for Loopback). Is this OK?

**Comment by dhmlau** [comment]
@ismirnov-ekoniva  thanks. I added a comment in https://github.com/strongloop/loopback.io/pull/1055#issuecomment-680091428 for signing the commit. 

To test it locally, you run:
```
bundle install
npm start
```

**Comment by ewrayjohnson** [comment]
I need this page fixed.  Would love to help but don't know how to fix.
