### ISSUE TITLE
Search not working in Firefox due to Same Origin Policy

### ISSUE THREAD

**Issue by russellsteadman** [loopbackio/loopback.io#1004]
## URL of the page 

[https://loopback.io/search/?q=%40property&sidebar=lb4_sidebar](https://loopback.io/search/?q=%40property&sidebar=lb4_sidebar)

## Nature of the issue 

Origin policy blocking load of search api via ajax.

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://us-south.functions.cloud.ibm.com/api/v1/web/dhmlau%40ca.ibm.com_dev/default/search.json?q=%40property&sidebar=lb4_sidebar. (Reason: CORS request did not succeed).
```

## Expected behavior

Search results would load. (User-Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0"`)

## Actual behavior

Perpetual loading screen.

## Suggested resolution

Seems like it could be multiple issues: https://stackoverflow.com/questions/24371734/firefox-cross-origin-request-blocked-despite-headers

**Comment by dhmlau** [comment]
@teamtofu, do you know if it only happens on Firefox? 
I tried it on Mac with Firefox and it seems to be fine.  Will try to get a Windows machine to reproduce this problem.
