### ISSUE TITLE
Verify that fenced blocks don't work in a blockquote

### ISSUE THREAD

**Issue by Sequoia** [loopbackio/loopback.io#105]
https://github.com/gettalong/kramdown/issues/374

**Comment by crandmck** [comment]
In general, I wouldn't think there would be much call for code blocks inside a block quote.  Is there an example?

**Comment by Sequoia** [comment]
https://github.com/strongloop/loopback-example-database/blob/oracle/README.md#automatic-path-modification

This is one of the two places I saw it. I filed an issue https://github.com/gettalong/kramdown/issues/374 & afterward found out that it _does_ appear to work, so my style guide entry might be inaccurate. I thought it wouldn't work-- now I think there was some other formatting issue breaking it (probably "no newline before fenced code block").

Normally I'd agree "why would this be a thing you'd do" but SL authors seem to really like blockquotes for a quick & dirty visual offset 😸

**Comment by crandmck** [comment]
> Normally I'd agree "why would this be a thing you'd do" but SL authors seem to really like blockquotes for a quick & dirty visual offset

Even it if _is_ technically legal markdown, I think we should discourage this and actively remove it when we see it.  There are better ways to achieve the same effect IMHO.  OTOH it's not end of the world if someone does it....Just looks silly. ;-)

**Comment by Sequoia** [comment]
Yeah I agree 100%. My response is "don't do that."

I'd said it wasn't possible in the guide tho & now that I know that it is I want remove that bit so the guide isn't full of falsehood. 😋
