### ISSUE TITLE
Duplicate page content titles in toc caused by translation.html

### ISSUE THREAD

**Issue by likexoo** [loopbackio/loopback.io#1069]
For example:
[Binding.md v4 zh](https://loopback.io/doc/zh/lb4/Binding.html)
[Getting-started.md v4 es](https://loopback.io/doc/es/lb4/Getting-started.html)

![image](https://user-images.githubusercontent.com/15852426/93661775-105bb600-fa8d-11ea-90cd-aaec3d1e0aee.png)
![image](https://user-images.githubusercontent.com/15852426/93661780-1b164b00-fa8d-11ea-8ba2-dddd5a40bad1.png)

All pages (What i have seen so far) with this problem use the following code in the configuration information at the head of the page:

```
layout: translation
```

So I checked the `translation.html` and found that deleting the following code will solve this problem:

```
{% unless page.toc == false %}
  {% include toc.html level=page.toc_level %}
{% endunless %}
```

I removed the code mentioned above and tested each page locally (Random tests for each language version) and found that this problem was solved.

**Comment by dhmlau** [comment]
@likexoo, thanks for submitting PR #1070. Since it's landed, I'm closing this issue as resolved.
