### ISSUE TITLE
Add CI branching info/rules

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#115]
## URL of the page

Add info from internal KB on CI/branching to http://loopback.io/doc/en/contrib/code-contrib.html
Not sure if it should be a section in this page or a "child" page.
## Nature of the issue

Per https://github.com/strongloop-internal/loopback-knowledge-base/pull/105, the information in the [CI branch rules](https://github.com/strongloop-internal/loopback-knowledge-base/blob/master/ci.branch-rules.md) page is useful to community contributors too, as it describes the reasons behind our decision to use latest in dev-dependencies.

Include info on project level things we decide that should be publicized, eg:
- How we use CI
- Why we have N branches in all repos
- Which branches are protected, etc 
## Suggested resolution

Just need to merge info from the internal KB page into loopback.io. 

cc @bajtos @superkhau

**Comment by superkhau** [comment]
CI should have it's own section IMO, or maybe listed under a section named "Infrastructure" with Ci as subsection, GitHub, etc).

**Comment by dhmlau** [comment]
PR has already merged.  Closing this issue.
