### ISSUE TITLE
Rework internal links

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#119]
Currently, links to other doc. pages are constructed as follows (for example):

```
[PersistedModel REST API](/doc/{{page.lang}}/lb2/PersistedModel-REST-API.html)
```

The original intent was to ensure that links go to the appropriate translation, but it is problematic for include templates (where the liquid variable `{{page.lang}}` is not allowed in a template parameter.

Also, when we duplicate the docs for the LB 3.0 release, we'll have to go through and replace `lb2` everywhere with `lb3`

However, due to the way we've set up the `pages` sub-folders, we _could_ just link to the page name, e.g. 

```
[PersistedModel REST API](PersistedModel-REST-API.html)
```

This will work for all languages and would not require any changes for LB3 (or other subsequent) releases.

**Comment by marc-ed-raffalli** [comment]
@crandmck I'm on it :)

**Comment by crandmck** [comment]
Thanks @marc-ed-raffalli !
