### ISSUE TITLE
I am new in loopback how can i upload image in data base with model and controller

### ISSUE THREAD

**Issue by VishalSingh28** [loopbackio/loopback.io#1202]
## URL of the page 

If applicable.

## Nature of the issue 

Is this an issue with the layout/behavior/UX of the site or a problem with missing/inaccurate documentation content?
In general, use this (loopback.io) repo for issues with layout/behavior/UX of the site, and other repos for doc content.

## Expected behavior

What did you expect to happen?

## Actual behavior

What actually happenend, with steps to reproduce (if applicable).

## Suggested resolution

How do you think this should be resolved (optional).

**Comment by dhmlau** [comment]
@VishalSingh28 , you might want to take a look at the file transfer example: https://github.com/strongloop/loopback-next/tree/master/examples/file-transfer, coming from https://loopback.io/doc/en/lb4/Examples.html.

btw, for further LoopBack 4 issues, please open it in https://github.com/strongloop/loopback-next. 
I'd also like to point you to our Slack workspace: https://join.slack.com/t/loopbackio/shared_invite/zt-8lbow73r-SKAKz61Vdao~_rGf91pcsw. It's a platform where the community users are helping each other. Hope it helps.

**Comment by dhmlau** [comment]
I believe your question has been answered. Closing as resolved. 
For further questions, please open an issue in  https://github.com/strongloop/loopback-next. Thanks.
