### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by kurly09** [loopbackio/loopback.io#1214]
## URL of the page 
https://loopback.io/doc/en/lb4/Calling-other-APIs-and-web-services.html

## Nature of the issue 

Is this an issue with the layout/behavior/UX of the site or a problem with missing/inaccurate documentation content?
In general, use this (loopback.io) repo for issues with layout/behavior/UX of the site, and other repos for doc content.

## Expected behavior

I need a latest documentation support.

## Actual behavior

What actually happenend, with steps to reproduce (if applicable).

## Suggested resolution

How do you think this should be resolved (optional).

**Comment by dhmlau** [comment]
@kurly09, thanks for reporting this. May I know where did you get the link from? 
The page was turned into separate pages for SOAP and REST services, so we've updated it. But it's possible that we've missed some places.

**Comment by dhmlau** [comment]
@kurly09, I found the reference https://loopback.io/doc/en/lb4/Calling-other-APIs-and-web-services.html in  https://loopback.io/doc/en/lb4/OpenAPI-connector.html#loopback-4-usage, and updated it. I'm closing this issue as fixed. Thanks.
