### ISSUE TITLE
Typo in Documentation

### ISSUE THREAD

**Issue by Ojvar** [loopbackio/loopback.io#1242]
Hello,
In the page: **https://loopback.io/doc/en/lb4/express-with-lb4-rest-tutorial.html**,

According to example, this snippet in document:

```
 // For testing purposes
  public async stop() {
    if (!this.server) return;
    await this.lbApp.stop();
    this.server.close();
    await pEvent(this.server, 'close');
    this.server = undefined;
  }
```
must be :
```
  // For testing purposes
  public async stop() {
    if (!this.server) return;
    await this.lbApp.stop();
    this.server.close();
    await once(this.server, 'close');
    this.server = undefined;
  }
```

Thanks

**Comment by VaishnaviMudaliar** [comment]
hey is this issue still open?? can I work on it??

**Comment by dhmlau** [comment]
@VaishnaviMudaliar, sorry about the late reply. 
Definitely! The source is coming from the loopback-next repo: https://github.com/loopbackio/loopback-next/blob/master/docs/site/express-with-lb4-rest-tutorial.md.
