### ISSUE TITLE
https://apidocs.loopback.io/loopback returns an "Internal Server Error".

### ISSUE THREAD

**Issue by buokae** [loopbackio/loopback.io#1246]
## URL of the page 
This happens at https://apidocs.loopback.io/loopback for instance, but it happes with every link on the main page at https://apidocs.loopback.io/.

## Nature of the issue 
Site returns an "Internal Server Error".

## Expected behavior
Show the LoopBack 3 api docs website.

## Actual behavior
Site returns an "Internal Server Error".

**Comment by dhmlau** [comment]
@buokae, thanks for reporting this. 
@raymondfeng, do you know where the LB3 apidocs are being hosted?

**Comment by buokae** [comment]
It seems to be working again, thanks!

**Comment by olivierwilkinson** [comment]
This appears to be happening again as I've just encountered it.

**Comment by DoReVo** [comment]
This is happening again for loopback 3
