### ISSUE TITLE
Documentation Change Logs are Frequently Outdated

### ISSUE THREAD

**Issue by bradharms** [loopbackio/loopback.io#1269]
**EDIT**: I have closed this and re-open it [here](https://github.com/loopbackio/loopback-next/issues/8120) for improved visibility.

## URL of the page 

https://loopback.io/doc/en/lb4/changelog.repository.html
(and possibly others)

## Nature of the issue 

The change logs for Loopback packages on the official documentation site sometimes go without any updates for a long time after new versions are published on npmjs.org. 

## Expected behavior

Change logs on the Loopback documentation website should *always* include information about the most recent versions of Loopback packages published on npmjs.org.

## Actual behavior

Today (2021-12-13), I have noted that @loopback/repository *4.0.0* was published *2021-11-18*, yet the change log at the time of this writing only reports up to version *3.7.3* and is dated for *2021-10-18*.

I have brought up this issue on Slack at #loopback-users and it is the second time I have done so. The first time was 2021-07-20.

Here are slack links to both of these previous reports:

- https://loopbackio.slack.com/archives/C01177XQN8N/p1626802414083800
- https://loopbackio.slack.com/archives/C01177XQN8N/p1639416915225600

## Suggested resolution

Updates to change log should be automatically published for new versions at the same time as (or possibly slightly before) the code version, possibly through the use of a web hook or other trigger. This process should occur automatically without human intervention so that it does not accidentally get skipped. Someone should verify that the documentation publication is up to date after the publish of the npmjs.org package updates.

**Comment by bradharms** [comment]
Re-opened at https://github.com/loopbackio/loopback-next/issues/8120

**Comment by achrinza** [comment]
Duplicate of https://github.com/loopbackio/loopback-next/issues/8120
