### ISSUE TITLE
typo in documentation

### ISSUE THREAD

**Issue by kidwm** [loopbackio/loopback.io#13]
In http://docs.strongloop.com/display/public/LB/Add+a+static+web+page

`/clientt/index.html` => `/client/index.html`

and in second `server/middleware.json` snippet, the curly brackets does not be paired, that makes confusing.

**Comment by raymondfeng** [comment]
Fixed. Thank you for reporting it.

**Comment by kidwm** [comment]
``` json
"files": {
    "loopback#static": {
      "params": "$!../client"
    }
  },
```

Thanks, could you also add the right bracket in the fourth line?

**Comment by crandmck** [comment]
Thanks @raymondfeng for fixing the typo.
@kidwm I added the missing curly brace.  Thanks again!
