### ISSUE TITLE
Add glossary / tooltips

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#138]
Add the glossary / tooltip implementation from https://github.com/ibm-apiconnect/getting-started where both are sourced from the same YAML data file.

Demo: https://ibm-apiconnect.github.io/getting-started/#demo-of-tooltips

Glossary: https://ibm-apiconnect.github.io/getting-started/glossary.html

**Comment by dhmlau** [comment]
https://github.com/ibm-apiconnect/getting-started is an archived repo already.  There won't be any active development on it unless it is really necessary.  Closing this ticket.
