### ISSUE TITLE
Add new Contributing page with corresponding navigation elements

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#14]
Per @altsang we want to have a new "Contributing" page that will contain the info I added in 4d335a276b43a0a70b04734caf79bb5218c695b7 and a bit more.  We will also need a "Contributing" navigation element in the header.  

I haven't been able to figure out how to add a new nav element without screwing up the layout, so please @rosshj could you do this in a new branch?  If you can add the nav element and new page, I can provide the content before we merge the PR.  Please go ahead and merge the `customers-tweaks` branch first so that can be live while we're working on this.

**Comment by rosshj** [comment]
@crandmck @altsang 

I'm concerned about the amount of navigation links are going into the header. It's starting to get a bit bloated. Usually you want to keep the main navigation focused and concise for not only keeping the design in check, but also clear for the user. With the addition of 'Who's Using' and now 'Contributing' we will be up to 6 + the Github star.

Maybe we can look into consolidating a couple of these sections?

Let me know. If you still want it up there, I will have to refactor the header design a bit to make room.

**Comment by rosshj** [comment]
In some cases (certain screen sizes) with the addition of 'Who's Using' it's already breaking.

![screen shot 2015-02-18 at 10 07 18 pm](https://cloud.githubusercontent.com/assets/723030/6262557/ad02cef6-b7ba-11e4-82fa-ebcc99edb760.png)

**Comment by crandmck** [comment]
Yes, I agree, but need to discuss with @altsang.  We could leave this stuff in the "Resources" page, put it somewhere else, orr rethink the nav entirely.

**Comment by crandmck** [comment]
Al noted that currently the "About" nav link is the same as the home page (and the LoopBack logo), so it's redundant.  He suggested that we could remove "About" and add "Contributing" without making the nav header too big.  Will that work?

**Comment by rosshj** [comment]
That could work. I will still need to adjust the header a little bit, but I should be able to squeeze all that in if we drop the 'About' section. We could always keep 'About' link in the footer nav.

**Comment by crandmck** [comment]
OK, please do that.  I think it's the best option at this point.  If you add a stub "Contributing" page in a branch, I will add the requisite content.

**Comment by crandmck** [comment]
@rosshj Do you need any more information to move forward on this?

**Comment by rosshj** [comment]
@crandmck @altsang Hey guys. I'm going to try and take a stab at this later tonight. 

Is there more content than just what appear on 'Contributing to LoopBack' section this page? http://loopback.io/resources/

**Comment by crandmck** [comment]
> Is there more content than just what appear on 'Contributing to LoopBack' section this page? http://loopback.io/resources/

That's all we have atm. We can probably add a bit more that's currently in the wiki.  I'll take a stab at it on the branch you just created.

**Comment by crandmck** [comment]
OK, in 2dcdefa7f8ad2f9aab4778d6e31f99c6fcee4a9b, I added a bit more content to the "Contributing" page.  I also changed the nav text from "Contributing?" to "Contributing" and changed the copyright to 2015 everywhere.

@altsang Do you want to take a look?

**Comment by altsang** [comment]
Yup will take a look, thx!

**Comment by crandmck** [comment]
I merged the PR, but Al said:

> would like to discuss what would be the appropriate section headers, specifically interested in adding a governance and maintainers section ASAP

Rather than open a new issue, will track that here.  I started a draft in the wiki based on Hapi Governance/Maintainers content: https://github.com/strongloop/loopback.io/wiki/Draft-%22Contributing%22-pages

@altsang Let's discuss or edit the page as you wish.

**Comment by altsang** [comment]
looks great!

I would just have a list of the maintainers that show Raymond, Ritchie,
Miroslav and Samuel, Fabien and Clark with links to the GH profiles.  The
purpose of this is to show that the project is not just all SL employees

-a-

On Mon, Mar 2, 2015 at 10:16 AM, Rand McKinney notifications@github.com
wrote:

> I merged the PR, but Al said:
> 
> would like to discuss what would be the appropriate section headers,
> specifically interested in adding a governance and maintainers section ASAP
> 
> Rather than open a new issue, will track that here. I started a draft in
> the wiki based on Hapi Governance/Maintainers content:
> https://github.com/strongloop/loopback.io/wiki/Draft-%22Contributing%22-pages
> 
> @altsang https://github.com/altsang Let's discuss or edit the page as
> you wish.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/strongloop/loopback.io/issues/14#issuecomment-76767754
> .

## 

Al Tsang
Co-Founder and CTO @ StrongLoop, Inc.

_StrongLoop http://strongloop.com/_\* makes it easy to **develop APIs
http://strongloop.com/mobile-application-development/loopback/** in Node,
plus get DevOps capabilities
http://strongloop.com/node-js-performance/strongops/ like monitoring,
debugging and clustering*_._

**Comment by crandmck** [comment]
OK, added the maintainers list to https://github.com/strongloop/loopback.io/wiki/Draft-%22Contributing%22-pages#loopback-lead-maintainers.  Question: by "Samuel" do you mean Sam Roberts?  He hasn't made many (any?) commits to LB, so not sure that's who you meant.

Also, Hapi makes a distinction between "Core contributors" and "community contributors" but it doesn't seem to make sense for us(?) Should I just delete that last paragraph--it's just confusing to me.

See two last paragraphs in https://github.com/strongloop/loopback.io/wiki/Draft-%22Contributing%22-pages#maintainers.

**Comment by altsang** [comment]
nope Samuel Reed - https://github.com/STRML

Yeah let's delete the last paragraph. I was confused by it too :)

Hopefully we can get some nice profiles displayed in a 2 x3 grid or
something

-a-

On Mon, Mar 2, 2015 at 12:58 PM, Rand McKinney notifications@github.com
wrote:

> OK, added the maintainers list to
> https://github.com/strongloop/loopback.io/wiki/Draft-%22Contributing%22-pages#loopback-lead-maintainers.
> Question: by "Samuel" do you mean Sam Roberts? He hasn't made many (any?)
> commits to LB, so not sure that's who you meant.
> 
> Also, Hapi makes a distinction between "Core contributors" and "community
> contributors" but it doesn't seem to make sense for us(?) Should I just
> delete that last paragraph--it's just confusing to me.
> 
> See two last paragraphs in
> https://github.com/strongloop/loopback.io/wiki/Draft-%22Contributing%22-pages#maintainers
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/strongloop/loopback.io/issues/14#issuecomment-76820985
> .

## 

Al Tsang
Co-Founder and CTO @ StrongLoop, Inc.

_StrongLoop http://strongloop.com/_\* makes it easy to **develop APIs
http://strongloop.com/mobile-application-development/loopback/** in Node,
plus get DevOps capabilities
http://strongloop.com/node-js-performance/strongops/ like monitoring,
debugging and clustering*_._

**Comment by crandmck** [comment]
Currently, the [governance branch](https://github.com/strongloop/loopback.io/tree/governance), just has a bullet list of lead maintainers.  But in #14 you said:

> Hopefully we can get some nice profiles displayed in a 2 x3 grid or something

I mocked up something using http://lab.lepture.com/github-cards/  
See http://screencast.com/t/Fk9Acz9pOIy

This was relatively easy, but if we want to (for example) change the background color or remove the "(Not) for hire" line, it would take a bit more work.  Let me know if you want to go with this, or wait...

**Comment by altsang** [comment]
heh - Rand the ever so resourceful.  Yeah this will work great, please take
your best stab and making something that blends in with the rest of the
background and the look and feel color-wise and yes please remove the gun
for hire tagline (or not for hire).  Good going!

-a-

On Tue, Mar 3, 2015 at 11:45 AM, Rand McKinney notifications@github.com
wrote:

> Currently, the governance branch
> https://github.com/strongloop/loopback.io/tree/governance, just has a
> bullet list of lead maintainers. But in #14
> https://github.com/strongloop/loopback.io/issues/14 you said:
> 
> Hopefully we can get some nice profiles displayed in a 2 x3 grid or
> something
> 
> I mocked up something using http://lab.lepture.com/github-cards/
> 
> See http://screencast.com/t/Fk9Acz9pOIy
> 
> This was relatively easy, but if we want to (for example) change the
> background color or remove the "(Not) for hire" line, it would take a bit
> more work. Let me know if you want to go with this, or wait...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/strongloop/loopback.io/issues/14#issuecomment-77019382
> .

## 

Al Tsang
Co-Founder and CTO @ StrongLoop, Inc.

_StrongLoop http://strongloop.com/_\* makes it easy to **develop APIs
http://strongloop.com/mobile-application-development/loopback/** in Node,
plus get DevOps capabilities
http://strongloop.com/node-js-performance/strongops/ like monitoring,
debugging and clustering*_._

**Comment by crandmck** [comment]
Well it turns out to be fairly difficult to restyle those GitHub "cards".   They don't have options to omit the "For hire" tag or change background color.  They are generated by a server-side Python script, so it's not just a matter of incorporating the JS and CSS.  I'm not sure how hard it would be grab the script and run it ourselves on the site, but I'm probably not the best person to do that.  

They do provide another "out of the box" theme that doesn't have the "For hire" tag, but the resulting cards are too large, and they don't seem to respect the height parameter.  Here's an example: http://screencast.com/t/mwvUEFmLu  

What do you think?
