### ISSUE TITLE
search feature isn't working on loopback.io

### ISSUE THREAD

**Issue by shubhamp-sf** [loopbackio/loopback.io#1410]
### Describe the bug

![image](https://user-images.githubusercontent.com/110156023/199952474-1d770b19-681d-44ec-aaaf-e1651fdfdccb.png)

### Reproduction

visit https://loopback.io/search/?q=datasource

**Comment by shubhamp-sf** [comment]
Now it says,
> Failed to get environments for Discovery.

![image](https://user-images.githubusercontent.com/110156023/201614324-544df872-abc3-458b-a293-5fc2993b1c91.png)

**Comment by shubhamp-sf** [comment]
@dhmlau, can it be fixed anytime soon? 
Search is a vital component of this site.

**Comment by dhmlau** [comment]
@shubhamp-sf, Thanks for bringing this up. I'm looking into Alogia as a replacement, and waiting for the invitation link.

**Comment by onurcagan** [comment]
Anyone looking into this? 
Docs without search functionality is really hard to navigate through, I'm looking to pick up lb4 but not being able to quickly look things up is bizarre.

**Comment by shubhamp-sf** [comment]
@onurcagan You can use `site:loopback.io/doc/en/lb4` prefix in your google search for now while this is being fixed.

It'll only load the pages from lb4 docs site.

For example if you're looking for where filter docs you can try this on google search: [`site:loopback.io/doc/en/lb4 where filter`](https://www.google.com/search?q=site%3Aloopback.io%2Fdoc%2Fen%2Flb4+where+filter)

**Comment by dhmlau** [comment]
sorry about the delay. The search is working now.

**Comment by shubhamp-sf** [comment]
Thanks @dhmlau for fixing the search, Is it possible to show only lb4 results when we're on `loopback.io/doc/en/lb4/`?

Currently it shows lb3 results on top every-time there is a match.

**Comment by dhmlau** [comment]
@shubhamp-sf, I noticed the lb3 content shows up in the search results too. I'm yet to find the right filter, might need to tag extra tags in our docs.

**Comment by dhmlau** [comment]
opened https://github.com/loopbackio/loopback.io/issues/1487 to track that
