### ISSUE TITLE
Add Connector REST documentation

### ISSUE THREAD

**Issue by Samox** [loopbackio/loopback.io#145]
## URL of the page 

http://loopback.io/doc/en/lb2/REST-connector.html
http://loopback.io/doc/en/lb2/Connector-hooks.html

## Nature of the issue 

There is no example of an implementation of the hooks used with the REST connector

## Expected behavior

A dedicated page for the hooks with the REST connector

## Suggested resolution

I have two examples in this [article](http://www.theodo.fr/blog/2016/10/the-loopback-rest-connector-and-its-secrets/) that could be shared. 
- How to get headers from a REST response
- How to handle statusCode from REST response

**Comment by crandmck** [comment]
Great suggestion, and thanks for offering the examples in the blog. I'll definitely add asap.
