### ISSUE TITLE
Please deploy the latest docs update to `loopback.io` 

### ISSUE THREAD

**Issue by shubhamp-sf** [loopbackio/loopback.io#1514]
I'm eager to see the merged PRs related to docs on loopback-next to be available on the site. Please update it. 🙂

**Comment by dhmlau** [comment]
@shubhamp-sf, we're working through some issues with publishing the release for loopback-next. Once it's resolved, we'll publish.

**Comment by shubhamp-sf** [comment]
Can it be published now that we have the things released on loopback-next?
