### ISSUE TITLE
API Docs are gone for LoopBack 4?

### ISSUE THREAD

**Issue by shubhamp-sf** [loopbackio/loopback.io#1528]
## URL of the page 

https://loopback.io/doc/en/lb4/apidocs.index.html

## Nature of the issue 

Missing API Docs pages (`https://loopback.io/doc/en/lb4/apidocs.*`).

## Expected behavior

It should show the API Docs Index and other packages' API references on respective links.

## Actual behavior

Shows "Page Not Found".

## Suggested resolution

__

**Comment by shubhamp-sf** [comment]
<img width="1376" alt="Screenshot 2023-07-13 at 9 19 47 AM" src="https://github.com/loopbackio/loopback.io/assets/110156023/e9fc61a6-a667-4155-989e-a20dc7a9ef52">

**Comment by achrinza** [comment]
Resolved in https://github.com/loopbackio/loopback.io/commit/86c839da6f38ae63fb77932dd531baec39d50f17
