### ISSUE TITLE
Fix redundant Twitter links

### ISSUE THREAD

**Issue by psjnek** [loopbackio/loopback.io#1568]
Screenshot:
![image](https://github.com/loopbackio/loopback.io/assets/94064167/767e951d-a3e0-462a-b9e3-250b4aef5020)

## Nature of the issue 

There are two tweet links on the footer which is confusing as they appear to do the same thing.

## Suggested resolution

I suggest that we remove one of the links.

**Comment by dhmlau** [comment]
@WebSnke, may I know where did you take the screencap? 

The footer of [loopback.io](https://loopback.io/) looks like below to me. The "tweet" related content are in blue.  
![Screenshot 2023-10-06 at 1 26 28 PM](https://github.com/loopbackio/loopback.io/assets/25489897/20ac21f4-6279-4790-bb3b-78b81c3e9c22)

**Comment by psjnek** [comment]
> @WebSnke, may I know where did you take the screencap?
> 
> The footer of [loopback.io](https://loopback.io/) looks like below to me. The "tweet" related content are in blue. ![Screenshot 2023-10-06 at 1 26 28 PM](https://user-images.githubusercontent.com/25489897/273288354-20ac21f4-6279-4790-bb3b-78b81c3e9c22.png)

Oh, ok. This is what the footer looks in my browser. I use Firefox 118 on Windows 10.

![image](https://github.com/loopbackio/loopback.io/assets/94064167/c02ec194-223f-4f40-b6cd-87cf78ac8ef1)

**Comment by dhmlau** [comment]
@WebSnke, saw you opened https://github.com/loopbackio/loopback.io/issues/1569. I'm thinking that it might be better to remove the 2 "Tweet" and "Follow @StrongLoop" altogether in the footer, as it's already in the header. Thoughts?

**Comment by moheyt** [comment]
Hey @dhmlau, could you please assign this task to me and label it as 'hacktoberfest' if possible?
