### ISSUE TITLE
Consolidate Redis connector doc

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#159]
I would like to move the information in https://github.com/strongloop/loopback.io/blob/gh-pages/pages/en/lb2/Redis-connector.md into https://github.com/strongloop/loopback-connector-redis/blob/master/README.md so we can have a single source for doc for this connector. 

Once we move the content into the connector README, I will copy the content of https://github.com/strongloop/loopback.io/blob/gh-pages/pages/en/lb2/redis-README.md into https://github.com/strongloop/loopback.io/blob/gh-pages/pages/en/lb2/Redis-connector.md (then delete redis-README.md from the loopback.io repo).

Then our Jenkins pipeline will ensure that the content from the README is automatically incorporated into the docs. 

cc @Amir-61

**Comment by smartmouse** [comment]
Not a high priority .

**Comment by ssh24** [comment]
Closing this. Follow the issue here: https://github.com/strongloop-internal/scrum-apex/issues/51
