### ISSUE TITLE
node21?

### ISSUE THREAD

**Issue by ivose** [loopbackio/loopback.io#1652]
Hi,

```
user@host:~/lpc$ lb4 app
Node.js "21.7.2" is not supported. Please use a version that satisfies "18 || 20".
```

Maybe you can also support to node v21? Comes and when comes also a new loopback version. E.g Loopback 5. lb4 looks like manym years old..

**Comment by achrinza** [comment]
Hi @ivose, you're probably looking for https://github.com/loopbackio/loopback-next

Our policy is to support Node.js LTS versions (i.e. Node.js 18, 20, etc.). Hence we do not guarantee support for Node.js odd-versions.

> . E.g Loopback 5. lb4 looks like manym years old..

We do not have any plans to release "LoopBack 5" as this would imply a heavy rewrite (Like in LB3->LB4)

LoopBack 4 remains actively-developed with new versions of its packages being released.
