### ISSUE TITLE
Add B of A logo to front page

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#17]
@altsang asked to replace the Sapient logo on the front page with B of A.  So, we need to replace the Sapient logo in http://loopback.io/images/logo-collage.jpg with B&W version of https://strongloop.com/wp-content/uploads/2015/01/baml.png.

**Comment by rosshj** [comment]
Opened a new PR https://github.com/strongloop/loopback.io/pull/18

**Comment by crandmck** [comment]
Thank you - merged!
