### ISSUE TITLE
Malicious gambling website url in docs

### ISSUE THREAD

**Issue by vytasgavelis** [loopbackio/loopback.io#1710]
## URL of the page 
https://loopback.io/doc/en/lb4/Defining-your-testing-strategy.html#define-your-testing-strategy

## Nature of the issue 

The docs reference an external resource about testing (labeled with: "The testing pyramid by Jonathan Rasmusson") which now is a malicious gambling website.

## Expected behavior
See a legit resource about testing

## Actual behavior
Got redirected to a malicious gambling website: https://www.agilenutshell.com/

## Suggested resolution
Remove this reference from the docs

**Comment by dhmlau** [comment]
@vytasgavelis, thanks for reporting this. When I clicked on the "The testing pyramid" link, it's blocked for me. 
Are you interested to submit a PR? Thanks.
