### ISSUE TITLE
All links pointing to strongloop.com are broken

### ISSUE THREAD

**Issue by harikrishnanp** [loopbackio/loopback.io#184]
## URL of the page 
http://loopback.io/doc/

## Nature of the issue 

All links pointing to https://strongloop.com are broken.
Eg: https://strongloop.com/strongblog/node-js-php-get-started/

## Expected behavior

The page should load fine with correct content.

## Actual behavior

`ERROR

The request could not be satisfied.

CloudFront wasn't able to connect to the origin. 
Generated by cloudfront (CloudFront)
Request ID: bLunFHWkVkUcY6kPhQsRuwzoa7mjMNx3WFBkY6KJvzG4FyXM261jsw==`

## Suggested resolution

Replace the broken links with correct one.

**Comment by crandmck** [comment]
I can't reproduce this, and I'm guessing it was a temporary issue with the strongloop site.  All these links work (as previously): 
- https://strongloop.com/strongblog/node-js-java-getting-started/
- https://strongloop.com/strongblog/node-js-ruby-on-rails-getting-started/
- https://strongloop.com/strongblog/node-js-php-get-started/

**Comment by harikrishnanp** [comment]
Yes. It was a temporary issue. It works fine now.
