### ISSUE TITLE
How to customize REST err handling in 3.0

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#214]
The 2.x doc explains how to [customize REST error handling](https://loopback.io/doc/en/lb2/Environment-specific-configuration.html#customizing-rest-error-handling) but with strong-error-handler, it's not clear how (or if!) one does this.

Need to update https://loopback.io/doc/en/lb3/Environment-specific-configuration.html#customizing-rest-error-handling accordingly.

@bajtos: @0candy said to check with you.

**Comment by bajtos** [comment]
strong-remoting still supports `errorHandler.handler` function, as described in docs.

```js
module.exports = {
  remoting: {
    errorHandler: {
      handler: function(err, req, res, next) {
        // custom error handling logic
        var log = require('debug')('server:rest:errorHandler'); // example
        log(req.method, req.originalUrl, res.statusCode, err);
        next(); // call next() to fall back to the default error handler
      }
    }
  }
};
```

However, `errorHandler.disableStackTrace` was removed in favour of `errorHandler.debug`.

IMPORTANT: this applies only when `remoting.handleErrors` is not `false` (i.e. not set or set to `true`). The current project template sets `remoting.handleErrors: false` ([source](https://github.com/strongloop/loopback-workspace/blob/e4c23d40414fc06a0e9137f0f6e224555e2f502a/templates/projects/empty-server/data.js#L82)) and therefore the above configuration options are ignored.

Users wishing to customise error handling should configure their own error-handling middleware in `server/middleware.json`.

I don't have a working example, here is a mock up (that may not work OOTB, sorry):

```js
// server/error-logger.js
module.exports = function(err, req, res, next) {
  var log = require('debug')('server:rest:errorHandler'); // example
  log(req.method, req.originalUrl, res.statusCode, err);
  next(err);
}

// server/middleware.json
{
  // ...
 "final:after": {
     "./error-logger.js": {}, // (I hope this works as I expect)
    "strong-error-handler": {}
}
```

If the users want to enable/disable console logs and/or enable/disable stack traces in the server responses, then they should change the configuration of strong-error handler in `server/middleware.json`.

```js
// server/middleware.json
{
  // ...
 "final:after": {
     "winston-error-handler": {}, // custom error logger
    "strong-error-handler": {
      "params": {
        "log": false
      }
    }
}
```

**Comment by bajtos** [comment]
Also note that both 2.x and 3.x applications are scaffolded with `handleErrors` set to `false`, therefore the current 2.x docs is not accurate either.

**Comment by crandmck** [comment]
DOes anything more need to be done in this area?

**Comment by bajtos** [comment]
Not as far as I am concerned. Let's wait for user feedback to see if there are any more improvements to be made.
