### ISSUE TITLE
Link to the docs in the header

### ISSUE THREAD

**Issue by n6g7** [loopbackio/loopback.io#23]
The website clearly lacks a big, visible link to the [docs](http://docs.strongloop.com/display/LB) in the header. I had to read all the way to the bottom of the [getting started](http://loopback.io/getting-started) page to finally find one (although I later found another one at the bottom of the main page) and it's kinda frustrating.

Why not have a menu that goes like `Getting started` `Examples` `Resources` **`Docs`** `Who's using?` `Contributing` ?
I'm sure I'm not the only one who has wasted a few precious minutes trying to find the docs. ;)

**Comment by rmg** [comment]
A direct link to the docs _would_ be nice, but I'm not sure there's room in the header and I'm not sure any of the current header links are unimportant enough to be demoted..

@as0n what about a big `Docs` button beside the `Get Started` button on the main landing page? Think that would be visible enough?

@crandmck thoughts?

**Comment by crandmck** [comment]
Thanks for the suggestion @as0n.  Agreed we need a more prominent link to the docs.

But as @rmg notes, we don't have any more room in the header.  I like the suggestion of a "Read Docs" button next to "Get Started".   Here's my suggestion: http://screencast.com/t/34gKJjIG

What do you think?  @ritch @rmg

**Comment by rmg** [comment]
@crandmck I think your proposal is worth deploying. For some reason I'm picturing the buttons each being a different colour, but I can't tell you what colours or which button should be witch. I say push what you've got and we can refine it later.

**Comment by n6g7** [comment]
@rmg @crandmck Yup I think a big button beside the `Get Started` would be great.

**Comment by crandmck** [comment]
OK, check it out.  Right now, it's the same color, etc, as the "Get Started" button, but I could make it a different color.... IMHO it looks OK as is, though.  I'll go ahead and close this.

**Comment by n6g7** [comment]
:+1:
