### ISSUE TITLE
Clarify future of Loopback and LB tools in documentation

### ISSUE THREAD

**Issue by doublemarked** [loopbackio/loopback.io#239]
## URL of the page 

https://loopback.io/doc/en/lb3/Installing-StrongLoop.html

## Nature of the issue 

Today in Gitter @juanmiret asked a question that is periodically asked in various forms:

![screen shot 2017-01-12 at 6 31 54 pm](https://cloud.githubusercontent.com/assets/239190/21898731/7a3d8baa-d8f6-11e6-97ea-75215ff732da.png)

He cited finding this on https://docs.strongloop.com/display/SLC/Deploying+applications+with+slc (which isn't redirecting correctly?) but I also see it at https://loopback.io/doc/en/lb3/Installing-StrongLoop.html, where it's stated right at the top that slc is deprecated.  It's kind of silly that it also then immediately warns you that APIC doesn't support Loopback 3.x. 

![screen shot 2017-01-12 at 6 44 13 pm](https://cloud.githubusercontent.com/assets/239190/21898927/25a99646-d8f7-11e6-9796-8450a183d130.png)

## Suggested resolution

There should be more clarity about the future of Loopback.

**Comment by juanmiret** [comment]
The thing that scares me out of using loopback is, right off the bat in getting started you have to use 'slc loopback', then 'slc loobpack:database', 'slc lb:model', 'slc deploy' etc etc, and then... 'slc will be deprecated', so... ok, what are the alternatives? Go use IBM APIC?

English is not my native language so excuse me if i'm not writing well 😄

**Comment by ghost** [comment]
Loopback continues to grow actively and the API Connect team at IBM is dedicated to develop, support and maintain the framework. Loopback is at the core of API Connect, has an active roadmap, and we have recently added several new members to the team. 

While we will indeed deprecate slc, we are in process of releasing Loopback’s own cli. You can watch its development at https://github.com/strongloop/loopback-cli

Additionally, API Connect will support the deployment functionality of slc, but loopback-cli will continue to support all Loopback functionality – current and new.

Hope that clarifies!

**Comment by doublemarked** [comment]
> Hope that clarifies!

@chandadharap sure, that clarifies things. Shouldn't this be more clear in the docs?

**Comment by crandmck** [comment]
As soon as `loopback-cli` is released (s/be soon IIUC) I'll update the docs.

**Comment by crandmck** [comment]
Based on the discussion, I'm going to change the title of this issue so as not to alarm anyone.... :-)

**Comment by ghost** [comment]
FYI loopback-cli is released on npmjs. @crandmck feel free to close this issue after documentation is updated.

**Comment by crandmck** [comment]
I should have the docs updated soon.  Will post here asap.

**Comment by crandmck** [comment]
Docs are updated!
