### ISSUE TITLE
Add meteor

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#25]
Add Meteor to http://loopback.io/resources/#compare

https://www.meteor.com/

**Comment by crandmck** [comment]
See working draft at https://github.com/strongloop/loopback.io/blob/gh-pages/resources/compare.md

**Comment by tenzan** [comment]
Thanks. I will share this with the Meteor community. ;)

**Comment by tenzan** [comment]
I think it's worth to mention about https://www.meteor.com/ddp

**Comment by crandmck** [comment]
@ritch Do you know anything about Meteor?  Can you help fill in https://github.com/strongloop/loopback.io/blob/gh-pages/resources/compare.md.  There are just a few missing items.

Also @chanda PTAL.

**Comment by ritch** [comment]
My knowledge is somewhat dated.

**Comment by ritch** [comment]
Afaik they don't have acls and they do have modules for extensions. I wouldn't mention the proprietary protocol (ddp).

**Comment by tenzan** [comment]
Some opinions from the Meteor forum https://forums.meteor.com/t/comparing-meteor-with-loopback-and-others/9566/3

**Comment by crandmck** [comment]
OK, I updated [the table](https://github.com/strongloop/loopback.io/blob/gh-pages/resources/compare.md) with the info from the above forum.  It looks reasonably complete now.  

@tenzan Please take a final look, and if you don't have any further suggestions I'll add it to the site.
@chandadharap @raymondfeng @altsang Final chance for input if you are interested.

**Comment by tenzan** [comment]
Thanks. I'll take a look and let you know.

**Comment by tenzan** [comment]
I got additional replies from the Meteor community at 
- https://forums.meteor.com/t/comparing-meteor-with-loopback-and-others/9566/7?u=tenzan
- https://forums.meteor.com/t/comparing-meteor-with-loopback-and-others/9566/8?u=tenzan

Recommended changes:
1. **Suitable For**: change from `web apps` to `Simple and Complex web apps`
2. **Extensions**: add also `NPM`
3. **Client SDKs**: add `React and Angular`
4. **Export API Definition**: It seems we could put `Yes` here according to the https://github.com/stubailo/meteor-rest/blob/master/packages/rest/README.md#listing-all-api-methods
5. **ACLs**: It seems Meteor supports a huge variety of authorisation options, starting with basic `allow/deny` built into the framework and including dozens of packages on Atmosphere.
6. **Data sources**: Regarding this I one I think, it'd be better, if you change to `Officially supports MongoDB, 3rd party packages available for MySQL and PostgreSQL`.

Hope this helps. :smile:

**Comment by crandmck** [comment]
Thanks.  I incorporated the above and a few other suggestions.

Updated http://loopback.io/resources/ with ff29899cd3c7451f1dfaf774188214ec5b84e545

**Comment by tenzan** [comment]
Thanks, guys! :smile:
