### ISSUE TITLE
Wrong ACL Name for deleting a record

### ISSUE THREAD

**Issue by jpbrown250** [loopbackio/loopback.io#252]
## URL of the page 
https://loopback.io/doc/en/lb2/Controlling-data-access.html

## Nature of the issue 
The ACL terms for how to define roles is inaccurate. The role for removing a record by ID is defined on the page as "destroyById" (which did not work). The one that does work for me is "deleteById".

Missing/inaccurate documentation content.

## Suggested resolution
change the text of the documentation.

**Comment by crandmck** [comment]
@jbrownssf Thanks for reporting the issue.

`destroyById` is an alias for `deleteById` - see https://github.com/strongloop/loopback/blob/master/lib/persisted-model.js#L359
They should both work, as should `removeById`.  

There is currently a bug in our API generation code that prevents the API docs from showing the aliases.

If it's not working for you, could you please provide a test case?
@smartmouse Any thoughts on why `destroyById` might not work?

**Comment by crandmck** [comment]
I'm going to move this issue to the loopback repo, because it's not a doc issue AFAICT.

**Comment by crandmck** [comment]
Issue moved to [strongloop/loopback #3133](https://github.com/strongloop/loopback/issues/3133) via [**ZenHub**](https://www.zenhub.com/)
