### ISSUE TITLE
A typo in "Use API Explorer" page

### ISSUE THREAD

**Issue by gamtiq** [loopbackio/loopback.io#255]
## URL of the page 

http://loopback.io/doc/en/lb3/Use-API-Explorer.html

## Nature of the issue 

Inaccurate documentation content.
There is the following sentence:
> Click on the *first* row, POST  /CoffeeShops    Create a new instance of the model and persist it into the data source to expand that operation:

But the `POST  /CoffeeShops` row is the third row in surrounding pictures.

**Comment by crandmck** [comment]
Fixed by a44f15fc23f06824ef37cd5ac4c82dd4dc8b1132
Thanks, @gamtiq
