### ISSUE TITLE
Update README links

### ISSUE THREAD

**Issue by superkhau** [loopbackio/loopback.io#260]
NOTE: We currently have redirects in place on docs.strongloop.com, so the below links are _not_ actually broken.  However, at some point docs.strongloop.com will go away altogether, and then we will need to fix all these links.

### loopback-example repos
- [ ] loopback-example-access-control/README.md:26:- [Getting started with LoopBack](http://docs.strongloop.com/display/LB/Getting+started+with+LoopBack)
- [ ] loopback-example-access-control/README.md:36:- [LoopBack models](http://docs.strongloop.com/display/LB/Defining+models)
- [ ] loopback-example-access-control/README.md:37:- [LoopBack adding application logic](http://docs.strongloop.com/display/LB/Adding+application+logic)
- [ ] loopback-example-angular/README.md:28:- [LoopBack AngularJS SDK](http://docs.strongloop.com/display/LB/AngularJS+JavaScript+SDK)
- [ ] loopback-example-angular/README.md:29:- [LoopBack models](http://docs.strongloop.com/display/LB/Defining+models)
- [ ] loopback-example-angular/README.md:30:- [LoopBack middleware](http://docs.strongloop.com/display/LB/Defining+middleware)
- [ ] loopback-example-app-logic/common/models/car.js:28:    // http://docs.strongloop.com/display/public/LB/Model+hooks#Modelhooks-afterInitialize
- [ ] loopback-example-app-logic/common/models/car.js:33:  // - http://docs.strongloop.com/display/public/LB/Operation+hooks
- [ ] loopback-example-app-logic/README.md:18:- [Getting started with LoopBack](http://docs.strongloop.com/display/LB/Getting+started+with+LoopBack)
- [ ] loopback-example-app-logic/README.md:24:- [LoopBack models](http://docs.strongloop.com/display/LB/Defining+models)
- [ ] loopback-example-app-logic/README.md:25:- [LoopBack adding application logic](http://docs.strongloop.com/display/LB/Adding+application+logic)
- [ ] loopback-example-app-logic/README.md:166:> Many other operation hooks are available, such as `access`, `before save`, `after save`, `before delete`, and `after delete`. See the [model operation hooks documentation](http://docs.strongloop.com/display/public/LB/Operation+hooks) for more information.
- [ ] loopback-example-app-logic/README.md:182:> We register `tracker` in the `initial` phase because we want it configured before other middleware. See the [official middleware phases documentation](http://docs.strongloop.com/display/LB/Defining+middleware#Definingmiddleware-Middlewarephases).
- [ ] loopback-example-database/README.md:147:via [*auto-migration*](https://docs.strongloop.com/display/public/LB/Implementing+auto-migration).
- [ ] loopback-example-database/README.md:219:> [*Discovery*](https://docs.strongloop.com/display/public/LB/Discovering+models+from+relational+databases)
- [ ] loopback-example-database/README.md:333:> See the [official docs](https://docs.strongloop.com/display/public/LB/Discovering+models+from+relational+databases)
- [ ] loopback-example-passport/server/views/pages/index.jade:9:      a.btn.btn-lg.btn-primary(href='http://docs.strongloop.com/display/public/LB/LoopBack#getting-started', role='button') View LoopBack docs »
- [ ] loopback-example-pubsub/README.md:6:- [Pub-sub documentation](http://docs.strongloop.com/display/MSG/Pub-sub)
- [ ] loopback-example-push/android/README.md:2:For documentation, see [StrongLoop Documentation - Push notifications for Android apps](http://docs.strongloop.com/display/DOC/Push+notifications+for+Android+apps).
- [ ] loopback-example-push/android/README.md:4:For information on creating the backend functionality, see [Creating push notifications](http://docs.strongloop.com/display/DOC/Creating+push+notifications).
- [ ] loopback-example-push/android/README.md:7:For more information, see the official [LoopBack Android SDK documentation](http://docs.strongloop.com/display/DOC/Android+SDK).
- [ ] loopback-example-push/android/README.md:12: * [LoopBack Node.js API Documentation](http://docs.strongloop.com/display/DOC/LoopBack+API)
- [ ] loopback-example-push/ios/README.md:2:For documentation, see [StrongLoop Documentation - Push notifications for iOS apps](http://docs.strongloop.com/display/DOC/Push+notifications+for+iOS+apps).
- [ ] loopback-example-push/ios/README.md:4:For information on creating the backend functionality, see [Creating push notifications](http://docs.strongloop.com/display/DOC/Creating+push+notifications).
- [ ] loopback-example-push/ios/README.md:7:For more information, see the official [LoopBack iOS SDK documentation](http://docs.strongloop.com/display/DOC/iOS+SDK+version+1.1).
- [ ] loopback-example-push/ios/README.md:12: * [LoopBack Node.js API Documentation](http://docs.strongloop.com/display/DOC/LoopBack+API)
- [ ] loopback-example-push/loopback/README.md:3:Please see the full documentation: [Creating push notifications](http://docs.strongloop.com/display/DOC/Creating+push+notifications).
- [ ] loopback-example-relations/README.md:23:- [LoopBack boot scripts](http://docs.strongloop.com/display/LB/Defining+boot+scripts)
- [ ] loopback-example-relations/README.md:24:- [LoopBack models](http://docs.strongloop.com/display/LB/Defining+models)
- [ ] loopback-example-relations/README.md:25:- [Loopback model relations](http://docs.strongloop.com/display/LB/Define+model+relations)
- [ ] loopback-example-relations/README.md:26:- [Creating loopback model relations](https://docs.strongloop.com/display/public/LB/Creating+model+relations)
- [ ] loopback-example-relations/README.md:293:> LoopBack [automatically derives](http://docs.strongloop.com/display/LB/BelongsTo+relations#BelongsTorelations-Overview)
- [ ] loopback-filters/README.md:34:**[Where](http://docs.strongloop.com/display/public/LB/Where+filter)**
- [ ] loopback-filters/README.md:52:Only include objects that match the specified where clause. See [full list of supported operators](http://docs.strongloop.com/display/public/LB/Where+filter#Wherefilter-Operators).
- [ ] loopback-filters/README.md:54:**[Geo Filter / Near](http://docs.strongloop.com/display/public/LB/Where+filter#Wherefilter-near)**
- [ ] loopback-filters/README.md:67:**[Order](http://docs.strongloop.com/display/public/LB/Order+filter)**
- [ ] loopback-filters/README.md:71:**[Limit](http://docs.strongloop.com/display/public/LB/Limit+filter) / [Skip](http://docs.strongloop.com/display/public/LB/Skip+filter)**
- [ ] loopback-filters/README.md:75:**[Fields](http://docs.strongloop.com/display/public/LB/Fields+filter)**
- [ ] loopback-filters/README.md:79:**Note: [Inclusion](http://docs.strongloop.com/display/public/LB/Include+filter) from loopback is not supported!**
- [ ] loopback-filters/README.md:83:[See the LoopBack docs](http://docs.strongloop.com/display/public/LB/Querying+data) for the filter syntax.
- [ ] loopback-ios-getting-started/LoopBackGuideApplication/LoopBackGuideApplication/FinaleView.xib:81:                <label opaque="NO" clipsSubviews="YES" userInteractionEnabled="NO" contentMode="left" text="docs.strongloop.com/loopback" lineBreakMode="tailTruncation" baselineAdjustment="alignBaselines" adjustsFontSizeToFit="NO" translatesAutoresizingMaskIntoConstraints="NO" id="104">
- [ ] loopback-ios-getting-started/LoopBackGuideSkeleton/LoopBackGuideApplication/FinaleView.xib:165:						<string key="IBUIText">docs.strongloop.com/loopback</string>

### loopback-connectors
- [ ] loopback-connector/docs/sql-connector.md:3:- [Database connectors](http://docs.strongloop.com/display/LB/Database+connectors) (for example, MongoDB, MySQL, Oracle).
- [ ] loopback-connector/docs/sql-connector.md:4:- [Non-database connectors](http://docs.strongloop.com/display/LB/Non-database+connectors) (for example, REST, SOAP).
- [ ] loopback-connector/docs/sql-connector.md:6:To build a new data source connector that doesn't yet exist, please see [Building a connector for a relational database](http://docs.strongloop.com/display/LB/Building+a+connector+for+a+relational+database).
- [ ] loopback-connector/README.md:7: * [Data sources and connectors](http://docs.strongloop.com/display/public/LB/Database+connectors)
- [ ] loopback-connector-db2/README.md:9:- All [CRUD operations](https://docs.strongloop.com/display/LB/Creating%2C+updating%2C+and+deleting+data).
- [ ] loopback-connector-db2/README.md:10:- [Queries](https://docs.strongloop.com/display/LB/Querying+data) with fields, limit, order, skip and where filters.
- [ ] loopback-connector-db2/README.md:25:Use the [data source generator](https://docs.strongloop.com/display/LB/Data+source+generator) (`slc loopback:datasource`) to add the DB2 data source to your application.
- [ ] loopback-connector-db2iseries/README.md:9:- All [CRUD operations](https://docs.strongloop.com/display/LB/Creating%2C+updating%2C+and+deleting+data).
- [ ] loopback-connector-db2iseries/README.md:10:- [Queries](https://docs.strongloop.com/display/LB/Querying+data) with fields, limit, order, skip and where filters.
- [ ] loopback-connector-db2iseries/README.md:24:Use the [data source generator](https://docs.strongloop.com/display/LB/Data+source+generator) (`slc loopback:datasource`) to add the DB2 data source to your application.
- [ ] loopback-connector-informix/README.md:13:- All [CRUD operations](https://docs.strongloop.com/display/LB/Creating%2C+updating%2C+and+deleting+data).
- [ ] loopback-connector-informix/README.md:14:- [Queries](https://docs.strongloop.com/display/LB/Querying+data) with fields, limit, order, skip and where filters.
- [ ] loopback-connector-informix/README.md:28:Use the [data source generator](https://docs.strongloop.com/display/LB/Data+source+generator) (`slc loopback:datasource`) to add the Informix data source to your application.
- [ ] loopback-connector-mssql/README.md:5:For complete documentation, see [StrongLoop Documentation | SQL Server Connector](http://docs.strongloop.com/display/LB/SQL+Server+connector).
- [ ] loopback-connector-mysql-jdbc/README.md:5:For complete documentation, see [StrongLoop Documentation | MySQL Connector](http://docs.strongloop.com/display/LB/MySQL+connector).
- [ ] loopback-connector-rest/README.md:11:For complete documentation, see [StrongLoop Documentation | REST Connector](http://docs.strongloop.com/display/LB/REST+connector).
- [ ] loopback-connector-soap/README.md:6:Please see the [official documentation](http://docs.strongloop.com/display/LB/SOAP+connector).
### angular sdk tools
- [ ] grunt-loopback-sdk-angular/README.md:31:[LoopBack AngularJS SDK documentation](http://docs.strongloop.com/display/LB/AngularJS+JavaScript+SDK#AngularJSJavaScriptSDK-Gruntplugin)
- [ ] gulp-loopback-sdk-angular/readme.md:49:http://docs.strongloop.com/display/LB/AngularJS+JavaScript+SDK

### loopback-components
- [ ] loopback-component-explorer/index.js:144:    'https://docs.strongloop.com/display/public/LB/Security+considerations'
- [ ] loopback-component-passport/README.md:11:> Please see the [official documentation](http://docs.strongloop.com/pages/viewpage.action?pageId=3836277) for more information.
- [ ] loopback-component-push/README.md:3: `![StrongLoop Labs](http://docs.strongloop.com/download/thumbnails/5310165/StrongLoop%20Labs%20Logo%20Cropped.png "StrongLoop Labs")`
- [ ] loopback-component-push/README.md:10:Please see the full documentation: [Push notifications](http://docs.strongloop.com/display/LB/Push+notifications).
- [ ] loopback-component-storage/lib/storage-service.js:26: * See the [documentation](https://docs.strongloop.com/display/LB/Storage+component) for more information.
- [ ] loopback-component-storage/README.md:15:> Please see the [Storage Service Documenation](http://docs.strongloop.com/display/public/LB/Storage+component).

### loopback-android-getting-started
- [ ] loopback-android-getting-started/LoopbackGuideApplication/res/values/strings.xml:12:        <a href="http://docs.strongloop.com/loopback">docs.strongloop.com/loopback</a>
- [ ] loopback-android-getting-started/LoopbackGuideSkeleton/res/values/strings.xml:12:        <a href="http://docs.strongloop.com/loopback">docs.strongloop.com/loopback</a>

### loopback-sdk-android
- [ ] loopback-sdk-android/DEVELOPING.md:32:Follow these steps to update the API documentation at http://docs.strongloop.com:
- [ ] loopback-sdk-android/docs/GettingStarted.md:4:[LoopBack Quick Start](http://docs.strongloop.com/loopback#quick-start).
- [ ] loopback-sdk-android/docs/GettingStarted.md:187: created [a model named "product"](http://docs.strongloop.com/loopback#model):
- [ ] loopback-sdk-android/docs/GettingStarted.md:199: 1. Go forth and develop! Check out the [API docs](http://docs.strongloop.com/loopback-android/api/index.html) or create more
- [ ] loopback-sdk-android/docs/GettingStarted.md:200: Models with the LoopBack [CLI](http://docs.strongloop.com/loopback#model) or
- [ ] loopback-sdk-android/docs/GettingStarted.md:201: [Node API](http://docs.strongloop.com/loopback#a-simple-example).
- [ ] loopback-sdk-android/docs/README.dist:13:    http://docs.strongloop.com/display/DOC/Android+SDK
- [ ] loopback-sdk-android/docs/Subclassing.md:22:leave any [custom behaviour](#http://docs.strongloop.com/strong-remoting) for
- [ ] loopback-sdk-android/README.md:3: `![StrongLoop Labs](http://docs.strongloop.com/download/thumbnails/5310165/StrongLoop%20Labs%20Logo%20Cropped.png "StrongLoop Labs")`
- [ ] loopback-sdk-android/README.md:9:[LoopBack](http://docs.strongloop.com/loopback) server application.  It enables you to interact with your
- [ ] loopback-sdk-android/README.md:13:See the official [LoopBack Android SDK documentation](http://docs.strongloop.com/display/LB/Android+SDK).

### loopback-sdk-angular
- [ ] loopback-sdk-angular/README.md:8:[LoopBack](http://docs.strongloop.com/loopback) server application.
- [ ] loopback-sdk-angular/README.md:15:documentation](http://docs.strongloop.com/display/LB/AngularJS+JavaScript+SDK)
- [ ] loopback-sdk-angular-cli/README.md:7:See the official [LoopBack AngularJS SDK documentation](http://docs.strongloop.com/display/LB/AngularJS+JavaScript+SDK)

### loopback-sdk-ios
- [ ] loopback-sdk-ios/docs/GettingStarted.md:13: Example App. [More information here.](http://docs.strongloop.com))
- [ ] loopback-sdk-ios/docs/GettingStarted.md:109: named "product"](http://docs.strongloop.com/loopback#model):
- [ ] loopback-sdk-ios/docs/GettingStarted.md:122: Models with the LoopBack [CLI](http://docs.strongloop.com/loopback#model) or
- [ ] loopback-sdk-ios/docs/GettingStarted.md:123: [Node API](http://docs.strongloop.com/loopback#a-simple-example).
- [ ] loopback-sdk-ios/docs/Subclassing.md:22:leave any [custom behaviour](#http://docs.strongloop.com/strong-remoting) for
- [ ] loopback-sdk-ios/docs/Subclassing.md:43:Since we've left [custom behaviour](#http://docs.strongloop.com/strong-remoting)
- [ ] loopback-sdk-ios/docs-1.0/GettingStarted.md:13: Example App. [More information here.](http://docs.strongloop.com))
- [ ] loopback-sdk-ios/docs-1.0/GettingStarted.md:109: named "product"](http://docs.strongloop.com/loopback#model):
- [ ] loopback-sdk-ios/docs-1.0/GettingStarted.md:122: Models with the LoopBack [CLI](http://docs.strongloop.com/loopback#model) or
- [ ] loopback-sdk-ios/docs-1.0/GettingStarted.md:123: [Node API](http://docs.strongloop.com/loopback#a-simple-example).
- [ ] loopback-sdk-ios/docs-1.0/README.md:5:See [LoopBack iOS SDK 1.0](http://docs.strongloop.com/loopback-clients/ios/api-1.0/annotated.html) for API reference documentation.
- [ ] loopback-sdk-ios/docs-1.0/Subclassing.md:22:leave any [custom behaviour](#http://docs.strongloop.com/strong-remoting) for
- [ ] loopback-sdk-ios/docs-1.0/Subclassing.md:43:Since we've left [custom behaviour](#http://docs.strongloop.com/strong-remoting)
- [ ] loopback-sdk-ios/README.md:3:`![StrongLoop Labs](http://docs.strongloop.com/download/thumbnails/5310165/StrongLoop%20Labs%20Logo%20Cropped.png "StrongLoop Labs")`
- [ ] loopback-sdk-ios/README.md:21:See also the [official iOS SDK documentation](http://docs.strongloop.com/display/LB/iOS+SDK).

### strong-remoting
- [ ] strong-remoting/lib/jsonrpc-adapter.js:153:      'https://docs.strongloop.com/display/public/LB/Security+considerations'
- [ ] strong-remoting/lib/rest-adapter.js:252:      'https://docs.strongloop.com/display/public/LB/Security+considerations'
- [ ] strong-remoting/lib/shared-method.js:19: * See also [Remote methods](http://docs.strongloop.com/display/LB/Remote+methods).
- [ ] strong-remoting/lib/shared-method.js:48: * [the docs](http://docs.strongloop.com/x/-Yw6#Remotemethods-HTTPmappingofinputarguments).
- [ ] strong-remoting/lib/shared-method.js:62: * [Loopback type](http://docs.strongloop.com/display/LB/LoopBack+types).
- [ ] strong-remoting/README.md:10:Also see the <a href="http://docs.strongloop.com/display/LB/Strong+Remoting">official StrongLoop documentation</a>.</div>

### juggler 

- [ ] loopback-datasource-juggler/intl/de/messages.json:41:  "ba0fd8106eb54de4d003a844206431fd": "Modellhook \"{0}\" ist veraltet, verwenden Sie stattdessen Operationshooks. {{http://docs.strongloop.com/display/LB/Operation+hooks}}",
- [ ] loopback-datasource-juggler/intl/en/messages.json:41:  "ba0fd8106eb54de4d003a844206431fd": "Model hook \"{0}\" is deprecated, use Operation hooks instead. {{http://docs.strongloop.com/display/LB/Operation+hooks}}",
- [ ] loopback-datasource-juggler/intl/es/messages.json:41:  "ba0fd8106eb54de4d003a844206431fd": "El gancho de modelo \"{0}\" está en desuso, utilice ganchos de operación en su lugar. {{http://docs.strongloop.com/display/LB/Operation+hooks}}",
- [ ] loopback-datasource-juggler/intl/fr/messages.json:41:  "ba0fd8106eb54de4d003a844206431fd": "Le point d'ancrage de modèle \"{0}\" est obsolète ; utilisez à la place les points d'ancrage d'opération. {{http://docs.strongloop.com/display/LB/Operation+hooks}}",
- [ ] loopback-datasource-juggler/intl/it/messages.json:41:  "ba0fd8106eb54de4d003a844206431fd": "L'hook del modello \"{0}\" è obsoleto, utilizzare gli hook dell'operazione. {{http://docs.strongloop.com/display/LB/Operation+hooks}}",
- [ ] loopback-datasource-juggler/intl/ja/messages.json:41:  "ba0fd8106eb54de4d003a844206431fd": "モデル・フック \"{0}\" は非推奨です。代わりに操作フックを使用してください。 {{http://docs.strongloop.com/display/LB/Operation+hooks}}",
- [ ] loopback-datasource-juggler/intl/ko/messages.json:41:  "ba0fd8106eb54de4d003a844206431fd": "모델 후크 \"{0}\"이(가) 더 이상 사용되지 않습니다. 오퍼레이션 후크가 대신 사용됩니다. {{http://docs.strongloop.com/display/LB/Operation+hooks}}",
- [ ] loopback-datasource-juggler/intl/nl/messages.json:41:  "ba0fd8106eb54de4d003a844206431fd": "Model hook \"{0}\" is gedeprecieerd; gebruik in plaats daarvan operation hooks. {{http://docs.strongloop.com/display/LB/Operation+hooks}}",
- [ ] loopback-datasource-juggler/intl/pt/messages.json:41:  "ba0fd8106eb54de4d003a844206431fd": "O gancho de modelo \"{0}\" está descontinuado, use ganchos de Operação no lugar. {{http://docs.strongloop.com/display/LB/Operation+hooks}}",
- [ ] loopback-datasource-juggler/intl/tr/messages.json:41:  "ba0fd8106eb54de4d003a844206431fd": "\"{0}\" model çengeli kullanımdan kaldırıldı, onun yerine işlem çengellerini kullanın. {{http://docs.strongloop.com/display/LB/Operation+hooks}}",
- [ ] loopback-datasource-juggler/intl/zh-Hans/messages.json:41:  "ba0fd8106eb54de4d003a844206431fd": "不推荐使用模型挂钩“{0}”，请改用操作挂钩。{{http://docs.strongloop.com/display/LB/Operation+hooks}}",
- [ ] loopback-datasource-juggler/intl/zh-Hant/messages.json:41:  "ba0fd8106eb54de4d003a844206431fd": "模型連結鉤 \"{0}\" 已淘汰，請改用作業連結鉤。{{http://docs.strongloop.com/display/LB/Operation+hooks}}",
- [ ] loopback-datasource-juggler/lib/dao.js:644: * [Where filter](https://docs.strongloop.com/display/LB/Where+filter#Wherefilter-Whereclauseforothermethods).
- [ ] loopback-datasource-juggler/lib/dao.js:647: * @param {Error} err Error object; see [Error object](http://docs.strongloop.com/display/LB/Error+object).
- [ ] loopback-datasource-juggler/lib/dao.js:1736: * See [Querying models](http://docs.strongloop.com/display/DOC/Querying+models) for more information.
- [ ] loopback-datasource-juggler/lib/dao.js:1770: * You can also use `and` and `or` operations.  See [Querying models](http://docs.strongloop.com/display/DOC/Querying+models) for more information.
- [ ] loopback-datasource-juggler/lib/datasource.js:568: * See [Model definition reference](http://docs.strongloop.com/display/DOC/Model+definition+reference) for details.
- [ ] loopback-datasource-juggler/lib/hooks.js:102:    '{{http://docs.strongloop.com/display/LB/Operation+hooks}}', hookName));
- [ ] loopback-datasource-juggler/lib/model-builder.js:600: * either the [type](http://docs.strongloop.com/display/LB/LoopBack+types) or `propertyName: {options}`
- [ ] loopback-datasource-juggler/lib/model-builder.js:602: * @property {String} type Datatype of property: Must be an [LDL type](http://docs.strongloop.com/display/LB/LoopBack+types).
- [ ] loopback-datasource-juggler/README.md:29:See the [official documentation](http://docs.strongloop.com).
- [ ] loopback-datasource-juggler/README.md:33:See [Advanced topics: data sources](http://docs.strongloop.com/display/LB/Advanced+topics%3A+data+sources).

### loopback-sdk-xamarin
- [ ] loopback-sdk-xamarin/README.md:7:- [Xamarin SDK documentation](http://docs.strongloop.com/display/LB/Xamarin+SDK)

### generator-loopback 
- [ ] generator-loopback/boot-script/templates/async.js:8:   * http://docs.strongloop.com/display/public/LB/Working+with+LoopBack+objects
- [ ] generator-loopback/boot-script/templates/sync.js:8:   * http://docs.strongloop.com/display/public/LB/Working+with+LoopBack+objects
- [ ] generator-loopback/README.md:13:[documentation](http://docs.strongloop.com/display/LB)
- [ ] generator-loopback/swagger/README.md:45:For more information, see http://docs.strongloop.com/display/LB/Getting+Started+with+LoopBack.

### loopback-boot
- [ ] loopback-boot/README.md:5:For full documentation, see the official StrongLoop documentation: [Defining boot scripts](http://docs.strongloop.com/display/LB/Defining+boot+scripts) and [Creating a LoopBack application](http://docs.strongloop.com/display/LB/Creating+an+application).
- [ ] loopback-boot/README.md:16:For more information, see [Defining boot scripts](http://docs.strongloop.com/display/LB/Defining+boot+scripts).

## loopback-model-*
- [ ] loopback-model/lib/hooks.js:94:    'http://docs.strongloop.com/display/LB/Operation+hooks');
- [ ] loopback-model/lib/model-builder.js:196:              'http://docs.strongloop.com/display/LB/Operation+hooks');
- [ ] loopback-model/lib/model-builder.js:600: * either the [type](http://docs.strongloop.com/display/LB/LoopBack+types) or `propertyName: {options}`
- [ ] loopback-model/lib/model-builder.js:602: * @property {String} type Datatype of property: Must be an [LDL type](http://docs.strongloop.com/display/LB/LoopBack+types).
- [ ] loopback-model-persistence/lib/dao.js:1336: * See [Querying models](http://docs.strongloop.com/display/DOC/Querying+models) for more information.
- [ ] loopback-model-persistence/lib/dao.js:1368: * You can also use `and` and `or` operations.  See [Querying models](http://docs.strongloop.com/display/DOC/Querying+models) for more information.

### Other
- [ ] loopback-swagger/README.md:7: - [slc loopback:swagger](https://docs.strongloop.com/display/LB/Swagger+generator)
- [ ] loopback.wiki/Contributing-documentation.md:1:See the [official guide for contributing to LoopBack documentation](http://docs.strongloop.com/display/public/LB/Contributing+to+LoopBack+documentation).
- [ ] loopback.wiki/Getting-help.md:1:1. [Check the Documentation](http://docs.strongloop.com)
- [ ] loopback.wiki/Home.md:3:This wiki contains basic guidelines for specific project-level topics. For usage related topics, see the [official documentation](http://docs.strongloop.com/display/LB/LoopBack).
- [ ] strong-pm/README.md:121:- [StrongLoop Documentation](http://docs.strongloop.com/display/SLC/Operating+Node+applications)

**Comment by crandmck** [comment]
NOTE: This is low-priority because docs.strongloop.com has redirects in place.  When the old site goes away, then these will be dead links, and we'll need to address this.

To do:
1. Replace any links to `docs.strongloop.com` with correct URL on `loopback.io/doc`
2. Replace link to `https://github.com/strongloop/loopback-example` with `https://loopback.io/doc/en/lb3/Tutorials-and-examples.html`

**Comment by dhmlau** [comment]
I just tried... most of the links no longer work. 
I'd like to close this issue due to inactivity.
