### ISSUE TITLE
Connecting model to data source page: db2 and db2z link points to the same URL

### ISSUE THREAD

**Issue by dhmlau** [loopbackio/loopback.io#271]
## URL of the page 

http://loopback.io/doc/en/lb3/Connecting-models-to-data-sources.html

## Nature of the issue 

Wrong URL for "loopback-connector-db2" link.

## Expected behavior

loopback-connector-db2 link in the table should point to https://www.npmjs.com/package/loopback-connector-db2

## Actual behavior

loopback-connector-db2 link in the table points to https://www.npmjs.com/package/loopback-connector-db2z

## Suggested resolution
update the link for "loopback-connector-db2"

**Comment by crandmck** [comment]
This was fixed by #272
