### ISSUE TITLE
Create Jekyll template for doc site

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#28]
We need a JavaScript widget that essentially duplicates the navigation panel on http://docs.strongloop.com.  The source of the nav content will be nested lists in markdown and the result at runtime should be a nice "expandable" navigation widget.

This is part of [Proposal to make LoopBack documentation open source](https://github.com/strongloop/loopback.io/wiki/Proposal-to-make-LoopBack-documentation-open-source).

**Comment by superkhau** [comment]
Big thumbs up! :clap:

**Comment by crandmck** [comment]
I found an excellent Jekyll theme that we should be able to leverage: http://idratherbewriting.com/documentation-theme-jekyll/ (source in https://github.com/tomjohnson1492/documentation-theme-jekyll).  This has almost everything we need and is MIT-licensed.  

Also, for comparison, this is _very close_ to what we're looking for: http://hamishwillee.github.io/jekyll-bootstrap-docsite/ (source in https://github.com/hamishwillee/jekyll-bootstrap-docsite).

**Comment by crandmck** [comment]
I'm going to close this, since we've chosen the `documentation-theme-jekyll` template and largely implemented it in http://loopback.io/doc/.
