### ISSUE TITLE
Update use of disableMethodByName

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#302]
[Authentication, authorization, and permissions](http://loopback.io/doc/en/lb3/Authentication-authorization-and-permissions.html#hiding-methods-and-rest-endpoints) still refers to `disableRemoteMethod` but in 3.0 this changes to `disableMethodByName` per http://loopback.io/doc/en/lb3/3.0-Release-Notes.html#clean-up-of-api-for-finding-and-disabling-remote-methods

Cf https://github.com/strongloop/loopback.io/pull/297#issuecomment-283571060

**Comment by crandmck** [comment]
@bschrammibm 
To disable a static remote method use [`ModelName.disableRemoteMethodByName('methodname')`](http://apidocs.strongloop.com/loopback/#model-disableremotemethodbyname) where `ModelName` is the name of the model and `methodname` is the name of the method.

To disable an instance (prototype) remote method, use: `ModelName.disableRemoteMethodByName('prototype.methodname')`

**Comment by bschrammIBM** [comment]
@bajtos The old command `disableRemoteMethod` is still in the loopback api reference at the following location: [https://apidocs.strongloop.com/loopback/#model-disableremotemethod](https://apidocs.strongloop.com/loopback/#model-disableremotemethod)
Just wanted to confirm it was supposed to remain in the API reference.

**Comment by bajtos** [comment]
> The old command disableRemoteMethod is still in the loopback api reference at the following location: https://apidocs.strongloop.com/loopback/#model-disableremotemethod
Just wanted to confirm it was supposed to remain in the API reference.

So far, `disableRemoteMethod` has been only deprecated, it wasn't removed yet. It would be great if API docs could show the method as deprecated. Alternatively, I am fine with removing the method from API docs (but still keeping it in the public API!).

**Comment by bschrammIBM** [comment]
@crandmck Is there a way to mark a method as "Deprecated" in the API docs?

**Comment by crandmck** [comment]
Yes, put "deprecated" in the doc comment in the code ;-)  I'll take care of that.

**Comment by bschrammIBM** [comment]
Closing this issue. The update is now posted on loopback.io/docs.
