### ISSUE TITLE
Document Bluemix generator CLI

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#307]
Need to doc new command/options to generate artifacts for LB app deployment to Bluemix.

IIUC, the cmd/option will be avail with both `lb` and `apic` in 5070.

**Comment by crandmck** [comment]
- Notes https://github.com/strongloop/loopback.io/wiki/LoopBack-Bluemix-native-tooling
- [x] Tech writer needs to clean up the informal provided docs (sync up with Yaapa)
- [x] Try out commands
  - [x] 3 Existing commands
  - [x] 1 Existing top level command
- [ ] Add examples for each command

**Comment by superkhau** [comment]
Timeboxed to 2.

**Comment by crandmck** [comment]
#334 is relevant PR.  Need to add more later.

I was unable to test `lb datasource --bluemix` because the `lb datasource` command because it wouldn't run.

After installing via `npm install -g strongloop/loopback-cli#command/bluemix-beta`

```
$ lb datasource
Unknown command "datasource"
Run "/usr/local/bin/lb --commands" to print the list of available commands.
```

**Comment by crandmck** [comment]
This is done.
