### ISSUE TITLE
Document SOAP discovery CLI

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#309]
CLIs will get a new command for discovering models from a SOAP WSDL.  This will work similar to the Swagger generator.  Talk to Rashmi.

**Comment by superkhau** [comment]
- [x] Tech writer needs to clean up the informal provided docs
- [x] Need example too in the docs (might need to sync up with @rashmihunt)

**Comment by crandmck** [comment]
Developer doc is https://github.com/strongloop/loopback-cli/blob/master/soap/README_Soap.md

**Comment by crandmck** [comment]
Added by https://github.com/strongloop/loopback.io/pull/353
