### ISSUE TITLE
Add Google Custom Search widget to new site

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#31]
Create and add something similar to https://docs.strongloop.com/display/APIC/Search+LoopBack+docs to the new doc site.

**Comment by doublemarked** [comment]
IMHO search is essential as the hierarchy of the docs is not always intuitive. Currently the search box isn't working - assuming it's known and related to this Issue.

**Comment by crandmck** [comment]
Yes @doublemarked it's known, and I agree it is absolutely essential.  I'm going to try to fix this today if I can.

**Comment by crandmck** [comment]
OK, 6deb3287e4b0daf6c86f616e03205b6de8395f72 added an initial implementation using Google Custom search.  I wanted to customize the CSS, and the only way I could figure out how to do that was to use the older version of GCS.  It seems to work OK, but I think we can still improve the look.   Help with CSS is appreciated.

Also, I don't like that every time you load a page, it displays "Loading" before displaying the search box...and sometimes doesn't load quickly.  The search results also look a bit wonky.  But at least it's functional now.

It's supposed to have autocomplete, but I haven't seen it working.. so not sure what's going on with that.

**Comment by crandmck** [comment]
I've marked this as "done" in #39 checklist, because it is functional.  However, there is room for cosmetic improvement so I'm going to leave this issue open for the time being.  Anyone with CSS-fu is welcome to make it look better.   See https://github.com/strongloop/loopback.io/blob/gh-pages/_includes/topnav.html and https://github.com/strongloop/loopback.io/blob/gh-pages/css/gcs.css for a start.

**Comment by crandmck** [comment]
On second thought, I'll go ahead and close this.  We'll just open separate issues for cosmetic or other improvements to the search feature.

**Comment by doublemarked** [comment]
Yea sure - functional and ugly is still functional :)
