### ISSUE TITLE
Correct/verify data source config containing object or array values

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#333]
In a [recent PR](https://github.com/strongloop/loopback.io/pull/319#discussion_r107362193) re this statement:

>Environment-specific configurations can override the top-level values with string and number values only. You cannot use objects or array values. 

@bajtos commented:

> This is not true - AFAIK, one can override object values with object values, array values with array values too.

This is mentioned in:
- https://loopback.io/doc/en/lb3/Attaching-models-to-data-sources.html#using-multiple-data-source-configurations
- https://loopback.io/doc/en/lb2/Environment-specific-configuration.html#data-source-configuration

Assuming this is true, then we should remove that statement.  Shall we confirm or can just we go on Miroslav's word? ;-)

**Comment by dhmlau** [comment]
@crandmck, I cannot find a definite answer by quickly looking at the code.  If @bajtos or @raymondfeng can confirm, that would be great.  Otherwise,  we might need to try it out to confirm.

Putting `apex` in the label so that we won't forget.

**Comment by crandmck** [comment]
OK thanks @dhmlau I went ahead and opened a PR with the doc change.  If it's not accurate, then we can just close the PR, or modify as needed.

**Comment by bajtos** [comment]
I have approved the patch, thank you @crandmck for taking care of this!

>  I cannot find a definite answer by quickly looking at the code

See [lib/config-loader.js](
https://github.com/strongloop/loopback-boot/blob/7f14a24ed289d3385652ecd4d4f59a633788901f/lib/config-loader.js#L254-L313) in the 2.x branch for the code that's implementing the merge strategy.

**Comment by dhmlau** [comment]
I guess it looks like the apex team doesn't need to do anything here?  Good to remove the `apex` label? Thanks.

**Comment by crandmck** [comment]
Thanks @bajtos PR landed.
