### ISSUE TITLE
Document how to use a global before-remote hook instead of middleware

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#336]
Per https://github.com/strongloop/loopback/issues/3286

---

> what I actually mean is that the model decoration needs to run when being accessed via the REST api through any relation as well as directly on the model REST api.

You can use a global remoting hook that's triggered for any method on any model. I think the code will look like this:

```js
app.remotes().before('**', (ctx, next) => {
  // do stuff with ctx.args.options
  next();
});
```

(IIRC, the handler method can return a promise instead of using `next` callback too.)

See also https://loopback.io/doc/en/lb3/Remote-methods.html#formattingremote-method-responses

I think it would be great to add a new section to that page explaining how to use a global before-remote hook instead of a middleware. /cc @crandmck

**Comment by karanssj4** [comment]
hi @crandmck, i think this can be achieved via mixins too.

> common/mixins/myMixin.js

```
module.exports = function(Model, options) {
  // Model is the model class
  // options is an object containing the config properties from model definition


  Model.beforeRemote('**', function(ctx, data, next) {
    // do whatever you want here
    next();
  });
};
```

and then attaching this in the required models as follows:

> common/models/my-model.js
```
{
 "name" : "myModel",
 .
 .
 "mixins": {
    "MyMixin":true
  }
// or
 "mixins": {
    "MyMixin": {
      "myOption": 1,
      "anotherOpt": 2
    }
  }
 .
 .
}
