### ISSUE TITLE
incorrect use of 'as' in polymorphic relations doc

### ISSUE THREAD

**Issue by ebarault** [loopbackio/loopback.io#337]
(cc: @crandmck, to keep track)

## URL of the page 
https://loopback.io/doc/en/lb2/Polymorphic-relations.html#hasmany-polymorphic-relations

## Nature of the issue 

the docs states:
```
{
Reader.hasMany(Picture, { polymorphic: { // alternative syntax  
  as: 'imageable', // if not set, default to: reference
  foreignKey: 'imageableId', // defaults to 'as - Id'
  discriminator: 'imageableType' // defaults to 'as - Type'
  } 
});
```

while this is actually what works for me:
```
  Reader.hasMany(Picture, {
    as: 'imageable', // if not set, default to: reference
    polymorphic: {
      foreignKey: 'imageableId', // defaults to 'as - Id'
      discriminator: 'imageableType' // defaults to 'as - Type'
  } 
});
```
(also i don't know what to think about this "default to: reference", this is not clear enough)

also this is false, we don't use the "as" keyword when using JSON definition
**UPDATE**: actually after some tests it's even quite dangerous to use the "as" keyword in json definition, and lead to unppredictible result
```
{
  "name": "Reader",
  "base": "PersistedModel",
  ...
  "relations": {
    "pictures": {
      "type": "hasMany",
      "model": "Picture",
      "polymorphic": {
        "as": "imageable", // <----- tested, this crashes the app
        "foreignKey": "imageableId",
        "discriminator": "imageableType"
       } 
    }
  }
...
```

additionally i think the following way to customize the relation name should also be added to the docs (without 'as') (this is more general, not only for polymorphic relations):
```
  Reader.hasMany("imageable", {
    model: Picture 
    polymorphic: {
      foreignKey: 'imageableId', // defaults to 'as - Id'
      discriminator: 'imageableType' // defaults to 'as - Type'
  } 
});
```

i'll also put imageables with an **s** as this is a hasMany relation

**Comment by bschrammIBM** [comment]
This code sample was changed in lb3, so no update was required.
I updated the code sample in Polymorphic-relations.md for lb2 as follows:
Reader.hasMany("imageables", {
    model: Picture 
    polymorphic: {
      foreignKey: 'imageableId', // defaults to 'as - Id'
      discriminator: 'imageableType' // defaults to 'as - Type'
  } 
});
