### ISSUE TITLE
broken link in Remote-methods.html#argument-descriptions

### ISSUE THREAD

**Issue by ebarault** [loopbackio/loopback.io#344]
## URL of the page 
https://loopback.io/doc/en/lb3/Remote-methods.html#argument-descriptions

## Nature of the issue 
![image](https://cloud.githubusercontent.com/assets/12000935/24700274/ea0ff012-19f6-11e7-8d7a-00bf0a54d9f4.png)
this link is broken

it should lead to https://loopback.io/doc/en/lb3/Remote-methods.html#http-mapping-of-input-arguments

**Comment by crandmck** [comment]
Thanks for catching, @ebarault
