### ISSUE TITLE
Need better examples of how to discover models from Relational DBs

### ISSUE THREAD

**Issue by bdharrington7** [loopbackio/loopback.io#347]
## URL of the page 

http://loopback.io/doc/en/lb3/Discovering-models-from-relational-databases.html

## Nature of the issue 
I'm not sure what the "other repos" being referred to are, but if this is the wrong spot I'd be happy to move this. 

I've been interested in how this works and despite the really simple database I was using that had a single table and two columns, I was a little confused about how this was supposed to actually work.

The docs say, "Use fs.writeFile() to save the output in common/models/model-name.json." Output of what? I'm assuming it was referring to the `models` parameter in the callback function for `discoverAndBuildModels`, but upon printing it to my console, it looks nothing like a model definition. After some digging it seems that `discoverSchema(s)` is closer to what I was expecting that output to be.

Another issue is that the example doesn't actually show how to write the files out, using information from the discovered models. I had to find this [Stackoverflow answer](http://stackoverflow.com/a/31312012) to get me pointed in the right direction.

I see this feature being pointed to from a lot of different places, so it doesn't seem to be some obscure feature, so either that's not true or I'm missing something.

**Comment by bdharrington7** [comment]
I'm finding that the name coming from `models.<Model>.definition.name` is coming in as Title case, and loopback doesn't like that. I originally created the model from scratch (using the CLI, which in turn created the world.**js** file (is there a way to create this programmatically as well?)), so would that have something to do with it?

**Comment by crandmck** [comment]
> ... Output of what? ...

I haven't looked at this in a while, but I believe it's referring to the output of `script.js`. That could certainly be clarified.

> Another issue is that the example doesn't actually show how to write the files out,

Yes, no one ever provided this example code. That would be a nice addition, if you want to provide the example code here, or just open a PR.

Also, I think we should add links to the discovery example code in https://github.com/strongloop/loopback-example-database/. There are examples for MySQL, Oracle, PostgreSQL, etc. (e.g. https://github.com/strongloop/loopback-example-database/tree/mysql/bin).

> it doesn't seem to be some obscure feature, so either that's not true or I'm missing something.

One reason this isn't documented more thoroughly is that you can do it without any coding using GUIs Arc (soon to be deprecated) or API Connect API Designer.  Of course, that's way easier, although it does require using a commercial (albeit free) product.

You might also try https://www.npmjs.com/package/loopback-discovery.  I haven't tried that myself, and I don't know the author, but it looks like it could be useful.

**Comment by bdharrington7** [comment]
I didn't see that loopback-discovery project before, and the other options you mentioned, but I will check them out

**Comment by hennzen** [comment]
Hate to do a simple +1 on this one, but since I experienced exactly the same like @bdharrington7 and spent time on digging on how to write my rather large MySQL schema into JSON models,  I feel tempted.

**Comment by officer-rosmarino** [comment]
This is the script I did to discover single tables. Maybe it can be useful to someone.

I'll attach the files here.

[discover-schema.txt](https://github.com/strongloop/loopback.io/files/1061007/discover-schema.txt)
Rename it to `.js`. I have this file in `/server/bin` and run it through `node discover-schema.js`.

The script requires a datasource name as specified in your `datasources.json` and a table name you want to discover.

**Comment by Vacster** [comment]
Great script by @honestserpent, it does exactly what one wants.

If anyone get an error saying 

> no such file or directory, open [model path]

try adding `{flag: 'w'}` as a parameter to the writeFileSync function on line 39 (which should be that by default but it wasn't working for me). This is done so one doesn't have to create an empty file for it to write on.

**Comment by artcoders27** [comment]
Please,
Can i get a little explanation for the next: 
"The script requires a datasource name as specified in your datasources.json and a table name you want to discover."
I understood datasource in datasource.js but where to put  table name?

Thanks!

**Comment by officer-rosmarino** [comment]
Just run the script, it will tell you what to do.

I put it in a gist: https://gist.github.com/honestserpent/a09f8a625aa1b142d31b62f22fef747b

**Comment by artcoders27** [comment]
honestserpent, thanks a lot.

I do not know what i am doing wrong, when i run the script, i got this:
"Usage: node discover-schema.js [-ds datasource -sn db_schema_name]
        -ds datasource: name of the datasource as specified in datasources.json
        -sn db_schema_name: name of the table in the db"

**Comment by officer-rosmarino** [comment]
@artcoders27 Make sure you use the script I provided in the [gist](https://gist.github.com/honestserpent/a09f8a625aa1b142d31b62f22fef747b).

How are you running the script. You should just be able to run it from the console by running:

`node discover-schema.js -ds [datasource] -tn [table_name]`

Say for instance that you named a datasource `hello-world-db` and you have a table in that db named `teams` that you want to discover.

Just run `node discover-schema.js -ds hello-world-db -tn teams`.

Hope this helps

**Comment by jpmyob** [comment]
@honestserpent - thx dude. I think this is gonna do what I needed, but im getting  

 error: '[node-ibm_db] SQL_ERROR',
  message: '[IBM][CLI Driver][DB2/LINUXX8664] SQL0206N  "LIVE.TBLADDRESS" is not valid in the context where it is used.  SQLSTATE=42703\r\n',
  state: '42S22'

Where I'm connecting to a DB2 where "live" is the schema and "tbladdress" is the table name.

I have tried w/ and w/o the schema so "live.tbladdress" "tbladdress" and all caps, all lower "LIVE.TBLADDRESS" "TBLADDRESS" - no luck

Any Ideas?

**Comment by officer-rosmarino** [comment]
Can you provide both the exact command you ran and your db structure?

**Comment by jpmyob** [comment]
@honestserpent - srry honest, this appears to be an issue with the API generator, not your discovery script. - I've got my model correct, I think, even if I do it manually - the API doesn't identify the correct table schema - I've logged a bug - https://github.com/strongloop/loopback.io/issues/623
but It doesn't have anything to do with your code.

**Comment by officer-rosmarino** [comment]
@jpmyob aight!

**Comment by jpmyob** [comment]
@honestserpent - circling back around, because I'm not getting any responses to my bug/post on numerous boards... When I run your script, I get a very similar error. So I'm hoping you might have some input - 

I'm connected to a DB2 (v10) database with multiple Schema. So when I run your code 
I'm a bit confussed by your -tn (table name) reference (above)... and -sn (schema name)
When I ran the script with -tn, I got errors, and so I tried -sn both, with and without the schema....

my db has one table I'm trying to use as a "learning / example" - LIVE.TBLADDRESS....

node server\bin\discover-schema.js -ds x3 -tn LIVE.TBLADDRESS

Usage: node discover-schema.js [-ds datasource -sn db_schema_name]
        -ds datasource: name of the datasource as specified in datasources.json
        -sn db_schema_name: name of the table in the db


node server\bin\discover-schema.js -ds x3 -sn LIVE -tn TBLADDRESS

Usage: node discover-schema.js [-ds datasource -sn db_schema_name]
        -ds datasource: name of the datasource as specified in datasources.json
        -sn db_schema_name: name of the table in the db


node server\bin\discover-schema.js -ds x3 -sn LIVE.TBLADDRESS
	{ 
		Error: [IBM][CLI Driver][DB2/LINUXX8664] SQL0206N  "LIVE.TBLADDRESS" is not valid in the context where it is used.  SQLSTATE=42703
		errors: [],
		error: '[node-ibm_db] SQL_ERROR',
		message: '[IBM][CLI Driver][DB2/LINUXX8664] SQL0206N  "LIVE.TBLADDRESS" is not valid in the context where it is used.  SQLSTATE=42703\r\n',
		state: '42S22' 
	}

my issue here, is the same as the issue I reference above, with the exception of the case that your discover script says it cannot identify the correct schema.table....

Ant thoughts?

**Comment by officer-rosmarino** [comment]
@jpmyob my code does not support multiple schemas.. The only 2 accepted options are `-ds` (database source) and `-tn` (table name).
Unfortunately, I never had the need to support multiple schemas so I didn't even think about it.. Plus, it's a very old script that I have implemented during my first period with Node.js and Javascript...

Now I don't even use loopback anymore so I am not supporting it in anyway, but if you want to take a look go through the code and check the `main` function at the end of the script.

Sorry I can't help more right now..

**Comment by al-k21** [comment]
Hello,

I am hitting the same issue.

> The docs say, `Use fs.writeFile() `to save the output in `common/models/model-name.json`. Output of what? I'm assuming it was referring to the models parameter in the callback function for discoverAndBuildModels, but upon printing it to my console, it looks nothing like a model definition. After some digging, it seems that discoverSchema(s) is closer to what I was expecting that output to be.

Could someone help?

**Comment by bajtos** [comment]
@al-k21 the documentation page is rather confusing, I'll take a look on improving it.

Meanwhile: If you want to discover a model definition (schema) and save it to a JSON file, then you need to use `dataSource.discoverSchema()` API. 

For example, when discovering [sample MySQL employees database](https://github.com/datacharmer/test_db), one can write the following code to obtain the definition of the `salaries` table:

```js
const schema = await db.discoverSchema(
  'salaries', // the table name
  {
    schema: 'employees' // the database/schema name
  },
);

await mkdirp('common/models');
await writeFile(
  'common/models/salaries.json',
  JSON.stringify(schema, null, 2)
);
```

See the full source code here: https://gist.github.com/bajtos/cafb7c9688b4f9b332bec661d088d7f7

The other API mentioned by our docs, `dataSource. discoverAndBuildModels()`, will define all discovered models on the datasource (the application). This way no model JSON file is needed and the models are created at runtime to match the current database schema.

**Comment by bajtos** [comment]
Hello, I opened a pull request to improve this part of our documentation, see https://github.com/strongloop/loopback.io/pull/670.

I'd love to hear your feedback - is the new content clear enough? Did I miss any important information?

**Comment by Fever905** [comment]
Is there any way to discoverSchema from an mssql stored procedure?  I am able to discover any table I feed it but I need to get the schema from a stored proc.  I'm open to a kludge :)

**Comment by bajtos** [comment]
> Is there any way to discoverSchema from an mssql stored procedure? I am able to discover any table I feed it but I need to get the schema from a stored proc. I'm open to a kludge :)

@Fever905 AFAIK, LoopBack can discover only tables and views, this applies to all connectors. 

I am not familiar with MSSQL stored procedures. Is there an SQL extension API allowing clients to introspect the output type of a stored procedure? If there is one, then it may be possible to build discovery of stored procedures on top of the existing code handling conversion from MS SQL types to LoopBack - see https://github.com/strongloop/loopback-connector-mssql/blob/442dd73dee7cc99a97f9da9613c2efcc35bd26a0/lib/discovery.js

Anyhow, this is off-topic here, could you please open a new issue in https://github.com/strongloop/loopback-datasource-juggler and mention my GH handle, so that I receive a notification?

**Comment by sdruckerfig** [comment]
What would be the syntax for discovering multiple specified views?

I tried:

let views = ["customerUser","adminOrders"];

  for (var i=0; i<views.length; i++) {
    
    dataSource.discoverAndBuildModels(
      views[i], 
      {
        relations: false,
        views: true
      },
      function(err, models) {
        if (err) return callback(err);

        // expose all new models via REST API
        for (const modelName in models) {
          let m = app.model(models[modelName], {
            dataSource: dataSource
          });
          restrictModelToReadOnlyEndpoints(m);
        }
        callback();
      });
  }

But I get an EADDR in use error when trying to discover more than one view.
