### ISSUE TITLE
Improve docs of Bluemix CLI commands/options

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#360]
Doc for the new `lb bluemix` command and `--bluemix` option are minimal.
 
It would be nice to add some information on some of the artifacts, even just reference links for:
-  `manifest.yml` file
- `Dockerfile` and `.dockerignore` files
- `.bluemix` dir and toolchain files

Eventually, I'd like to add an example or perhaps a new chapter in "Getting Started" that walks through deploying to Bluemix. 

Also, add references to https://github.com/strongloop/loopback-example-bluemix.

**Comment by hacksparrow** [comment]
https://github.com/strongloop/loopback.io/pull/421 addressed this.
