### ISSUE TITLE
Link broken 

### ISSUE THREAD

**Issue by aseem2625** [loopbackio/loopback.io#363]
Following link is broken.
https://loopback.io/doc/en/lb3/Model-hooks.html

The above link's anchor is given in https://loopback.io/doc/en/lb3/LoopBack-core-concepts.html#models

<img src="https://cloud.githubusercontent.com/assets/6055628/25306745/25ffc47c-27b1-11e7-92e4-a71b6fa70198.png"  width=300 />

**Comment by crandmck** [comment]
Fixed by #364
