### ISSUE TITLE
Migrate translated content

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#37]
In addition to the English content (which is mostly migrated--still some work to do, but maybe 80% done atm), we need to migrate community-translated content from Confluence to Jekyll/Markdown in the following languages:
- Chinese: https://docs.strongloop.com/display/zh
- French: https://docs.strongloop.com/display/FR/LoopBack
- Japanese: https://docs.strongloop.com/display/JA/LoopBack
- Korean: https://docs.strongloop.com/display/ko/LoopBack
- Russian: http://docs.strongloop.com/display/RU/LoopBack

NOTE: even though we have https://docs.strongloop.com/display/PTBR, there doesn't seem to be any content translated into Portuguese, so there's nothing to migrate.

Several caveats:
- In every language, only part of the content has been translated, so we need to migrate only the translated articles.
- For untranslated content, we should just have the English content.
- Depending on the language, some/all titles in the sidebar navigation has been translated, and sometimes not.

ASAP, I will export the translated content, and (time permitting) run the migration script and check in the markdown files.  If I run into problems, I may need to ask for help from @marc-ed-raffalli again :-)

I need to write up a short explanation about how people can contribute translations (for both existing and new languages).  Cf https://github.com/strongloop/loopback.io/issues/33.

**Comment by crandmck** [comment]
I think we're ready for the final phase: QA / testing of the content.

**Comment by jaimeneeves** [comment]
@crandmck  what's the first step that I have to follow, because I'm going to do the translation to Portuguese?

**Comment by crandmck** [comment]
Hi @dejaneves The first step is for me (with help from anyone who wants to contribute) to clean up the English content, since that's what you'll translate from.  We're close to being "done" with that.  Then, I'll create a section where you can translate the articles "in place" to Portuguese and I'll provide simple instructions.  

It should just be a little longer... thanks for your patience!

**Comment by crandmck** [comment]
OK, it turns out that there is also no existing translated content for French, in addition to Portuguese. 

I imported the [Russian](http://loopback.io/doc/ru/lb2/) and [Japanese](http://loopback.io/doc/ja/lb2/) content, and created stub areas for [French](http://loopback.io/doc/fr/lb2/), [Portuguese](http://loopback.io/doc/pt-br/lb2/), and [Korean](http://loopback.io/doc/ko/lb2/).

I ran out of time to actually add the Korean content.  But here's a zip with the converted files:
[ko-export.zip](https://github.com/strongloop/loopback.io/files/490526/ko-export.zip)

I created the [Chinese](http://loopback.io/doc/zh/lb2/) "space" but ran into problems running the migration script on the Chinese content @marc-ed-raffalli. I'm attaching the zip file of the Confluence HTML export:

[zh-Confluence-space-export-211432-851.html.zip](https://github.com/strongloop/loopback.io/files/490527/zh-Confluence-space-export-211432-851.html.zip)

I realize the script was created for English content, but it worked reasonably well for Russian, Korean, and Japanese.

The error was:

```
...
Found invalid JSON/JS code tagged as js in file Installing-the-Oracle-connector_6094965.html
Found invalid JSON/JS code tagged as js in file Oracle-connector_6094964.html
/Users/rand/StrongLoop/Confluence-export/confluence-to-jekyll/src/content-conversion-flow/md-converter/converters/info-macros-conversion.js:27
      var iconClassName = node.querySelector('.aui-icon').classList.item(1)
                                                         ^
TypeError: Cannot read property 'classList' of null
    at Function.replacement (/Users/rand/StrongLoop/Confluence-export/confluence-to-jekyll/src/content-conversion-flow/md-converter/converters/info-macros-conversion.js:27:58)
    at process (/Users/rand/StrongLoop/Confluence-export/confluence-to-jekyll/node_modules/to-markdown/index.js:182:31)
    at toMarkdown (/Users/rand/StrongLoop/Confluence-export/confluence-to-jekyll/node_modules/to-markdown/index.js:216:5)
    at mdConverter (/Users/rand/StrongLoop/Confluence-export/confluence-to-jekyll/src/content-conversion-flow/md-converter/index.js:6:10)
    at module.exports (/Users/rand/StrongLoop/Confluence-export/confluence-to-jekyll/src/content-conversion-flow/steps/html-to-md.js:17:12)
    at nextTask (/Users/rand/StrongLoop/Confluence-export/confluence-to-jekyll/node_modules/async/dist/async.js:5021:18)
    at /Users/rand/StrongLoop/Confluence-export/confluence-to-jekyll/node_modules/async/dist/async.js:5015:17
    at /Users/rand/StrongLoop/Confluence-export/confluence-to-jekyll/node_modules/async/dist/async.js:339:31
    at /Users/rand/StrongLoop/Confluence-export/confluence-to-jekyll/node_modules/async/dist/async.js:847:20
    at module.exports (/Users/rand/StrongLoop/Confluence-export/confluence-to-jekyll/src/content-conversion-flow/steps/attachments-migration.js:46:3)
```

**Comment by crandmck** [comment]
For instructions one what you need to do to use the exported/converted content, see [Importing existing translations](http:loopback.io/doc/en/contrib/Adding_a_new_language.html#importing-existing-translations).

**Comment by marc-ed-raffalli** [comment]
Hi @crandmck, the script should be language agnostic.
What I suspect is the markup has some differences, will check that out and send an MR for each

**Comment by marc-ed-raffalli** [comment]
I created the MR https://github.com/strongloop/loopback.io/pull/74

The root of the issue was the macro were assumed to all have an icon. 
But in these pages, 7 had a macro without icon.

Also, fair to you @crandmck, the script has hard codded `en`, could be more agnostic ;)
I left the original file name when it contains chinese / special chars.

**Comment by nuba** [comment]
Muito bom! Awesome! Really happy to see this up! The old wiki thing with the shared account and login workarounds wasn't really cutting it for a community-driven translation effort. Hope we'll get things going now! :)

**Comment by crandmck** [comment]
I'm closing this issue since most of the existing content has been migrated.  If there are any more questions or issues around translation, please just open a new issue... Thanks!
