### ISSUE TITLE
Notify community when ready to accept translation PRs.

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#38]
This will be a general issue to notify the community when we're ready to accept translation PRs.  
See #37 for more details on localization. 

Please comment here if you're interested in translating LoopBack docs so you'll receive a GH notification.

@dejaneves This issue replaces https://github.com/strongloop/loopback/issues/2700 and I'll comment here when we're ready to accept translation PRs.

**Comment by jaimeneeves** [comment]
ok

**Comment by PhilippeCorreges** [comment]
Of course I would be keen to participating in FR translations as I used to.

Kind Regards,

**Comment by marc-ed-raffalli** [comment]
I can help reviewing FR content

**Comment by qxl1231** [comment]
![image](https://cloud.githubusercontent.com/assets/8305742/18373042/59655736-7673-11e6-83e8-b8297b74c7b2.png)
it's me, and im coming up!

im in!

**Comment by crandmck** [comment]
Hello, folks interested in translation....I ran into a blocker to get localization working: #47.   I Googled a bit, but didn't find anything obvious.  By default Jekyll uses UTF-8 encoding, but I think it's an issue with Liquid.

I would appreciate any help!  

NOTE: This turned out to be pilot error, and is not a blocker for localization.

**Comment by crandmck** [comment]
Hello everyone.  I'm happy to say that the site is ready to accept translation PRs!

In case you haven't noticed, I recently added a "Translations" dropdown selector in the top bar, and added some languages as examples.  I documented the basic structure and process in:
- http://loopback.io/doc/en/contrib/Adding_a_new_language.html
- http://loopback.io/doc/en/contrib/Translating_articles.html

The French and Portuguese spaces are totally empty.  The Russian and Japanese spaces have some translated content. Japanese has only two articles, and it has the English navigation sidebar.  Russian need quite a bit of cleanup; its sidebar was generated by the migration script.  For a summary of what needs to be done, see [Importing existing translations](http://loopback.io/doc/en/contrib/Adding_a_new_language.html#importing-existing-translations)

For Korean and Chinese, see my [comments on issue 37](https://github.com/strongloop/loopback.io/issues/37#issuecomment-249284115)

NOTE:  We don't _have_ to use the existing translated content; we could just start from scratch with Korean and Chinese. I'll leave it up to speakers of those languages to decide what makes the most sense.

I'll probably close this issue soon, but I'll leave it open for a while in case there are any questions.

**Comment by PhilippeCorreges** [comment]
Can i start on French translation ?

Philippe

**Comment by crandmck** [comment]
@PhilippeCorreges Yes!  Please read the articles linked to above, and let me know if you have any questions.  We're kind of figuring out the process as we go, so please be patient....I _think_ I've explained how to do everything, but there might be gaps, and some of the process may change along the way.

**Comment by qxl1231** [comment]
For Korean and Chinese, see my comments on issue 37 . so Chinese translation still need waiting ha

**Comment by crandmck** [comment]
@qxl1231 I don't see any comments from you on #37...?  

For Chinese, I was hoping you or someone else could help with the [errors from the conversion script](https://github.com/strongloop/loopback.io/issues/37#issuecomment-249284115) with the Chinese content.

For Korean, the conversion worked (see the zip file attached to #37) but the converted content needs to be cleaned up and added to the repo.  I can do that, but it will be a while before I can devote any time to it.  If anyone wants to give it a go in the meantime, that would be great.

**Comment by qxl1231** [comment]
@crandmck  #37 i have know it ,but cant find any help infomation for this error

**Comment by crandmck** [comment]
I'm hoping that @marc-ed-raffalli, who wrote the conversion code, can help...

**Comment by crandmck** [comment]
I'm going to close this issue.  Feel free to open new issues if/when problems occur around translation.
