### ISSUE TITLE
Document excludeBaseProperties model property

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#380]
Per https://github.com/strongloop/loopback-datasource-juggler/pull/1371 and https://github.com/strongloop/loopback-workspace/issues/486, a new excludeBaseProperties model  property has been added, and we need to document it.

At a minimum, add the property to http://loopback.io/doc/en/lb3/Model-definition-JSON-file.html. 
But look into where else it should be mentioned.

**Comment by rashmihunt** [comment]
Fixed using issue https://github.com/strongloop-internal/scrum-asteroid/issues/191
My PR for this work - https://github.com/strongloop/loopback.io/pull/386
