### ISSUE TITLE
Cannot automigrate models with change tracking enabled

### ISSUE THREAD

**Issue by officer-rosmarino** [loopbackio/loopback.io#384]
## URL of the page 

[https://loopback.io/doc/en/lb3/Synchronization.html#enable-change-tracking](https://loopback.io/doc/en/lb3/Synchronization.html#enable-change-tracking)

## Nature of the issue 

I want to be able to perform bulk updates and I have found out in the documentation that I need to enable change tracking.
In order to do so the documentations says I have to update the models I want to be able to track changes of, and that **for each change-tracked model, a new model (database table) is created to contain change-tracking records**, but I am not sure when and how this model will be created.

## Expected behavior

To migrate just fine when I perform migration on a model where I have enabled change tracking.

## Actual behavior

`datasource.automigrate` throws an `error: relation "public.[model-name]-change" does not exist
` error on automigration when i run automigration.

## Steps to reproduce

1. run `$ lb model test-model`, create a model and attach it to a datasource (mine is postgres)
2. change the model definition in test-model.json in order to enable change-tracking, according to [this](https://loopback.io/doc/en/lb3/Synchronization.html#enable-change-tracking):
2.1 Set `trackChanges` to `true`.
2.2 Change the `id` property to an auto-generated GUID; for information on GUIDs
2.3 Set `strict` property to `validate`
2.4 Set the `persistUndefinedAsNull` property to `true`.
3. Perform automigration to export the model to the db 
[https://loopback.io/doc/en/lb3/Creating-a-database-schema-from-models.html](https://loopback.io/doc/en/lb3/Creating-a-database-schema-from-models.html)
4. **Get the following error:**
```
events.js:163
    throw er; // Unhandled 'error' event
    ^
    error: relation "public.test_model-change" does not exist
    [...]
```

**Comment by crandmck** [comment]
Not clear that this is a doc issue.  Sounds more like an issue with sync?
@strongloop/sq-lb-asteroid

**Comment by bajtos** [comment]
Yes, this looks like a bug in loopback-datasource-juggler and/or loopback-connector-postgresql to me. @kjdelisle  @strongloop/sq-lb-apex could you PTAL?

**Comment by cgole** [comment]
Issue moved to [strongloop/loopback-datasource-juggler #1403](https://github.com/strongloop/loopback-datasource-juggler/issues/1403) via [**ZenHub**](https://www.zenhub.com/)
