### ISSUE TITLE
Contradictory docs on User model

### ISSUE THREAD

**Issue by f-w** [loopbackio/loopback.io#394]
## URL of the page 

https://loopback.io/doc/en/lb3/Managing-users.html

## Nature of the issue 

This page stated

> You must create your own custom model (named something other than “User,” for example “Customer” or “Client”) that extends the built-in User model rather than use the built-in User model directly.

But everywhere else in the docs, User model is used directly. For example, see https://loopback.io/doc/en/lb3/Introduction-to-User-model-authentication.html.

Also, if I use *lb* cli to scaffold an app, the User model is created by default.

## Suggested resolution

Clearify!

**Comment by crandmck** [comment]
> ...everywhere else in the docs, User model is used directly.
 
@superkhau This is a good point.  I think all the example repos (and thus related docs) just use the User model, which is not best practice.

> Also, if I use lb cli to scaffold an app, the User model is created by default.

Yes, all the built-in models are created by default.  That's expected and I believe the docs reflect this.

**Comment by superkhau** [comment]
@crandmck It is recommended to extend the builtin User model for customization. If you're OK with email and password as the only fields, then you are free to use the builtin Model.

**Comment by crandmck** [comment]
Right, OK. I think the way it's stated now is too broad--we need to be more specific about why we recommend extending User, rather than using it directly.

@f-w Would clarifying above address your confusion?

**Comment by f-w** [comment]
Yes. I think toning down the quoted statement is needed.

**Comment by crandmck** [comment]
OK, I'll make that change, thx.

**Comment by crandmck** [comment]
OK, I clarified the wording as above in several pages that had this note, e.g. http://loopback.io/doc/en/lb3/Using-built-in-models.html.  

I'll assume that this addresses this issue; closing.
