### ISSUE TITLE
Annotator errors

### ISSUE THREAD

**Issue by doublemarked** [loopbackio/loopback.io#40]
This is minor, but all pages I've loaded are producing the following error on the console:

`Uncaught TypeError: $(...).annotator is not a function`

The offending code is the following page-end script,

```
    <script>
    jQuery(function ($) {
        $('.post-content').annotator()
                .annotator('setupPlugins', {tokenUrl: 'http://example.com/api/token'})
    });
    </script>
```

This does not appear to be impacting anything, but may be a sign of something missing/broken that you guys know about.

**Comment by crandmck** [comment]
Thanks, I wasn't aware of this.  I'll look into it.

**Comment by crandmck** [comment]
Ha, this appears to be a bogus script introduced by the Jekyll template author: https://github.com/tomjohnson1492/documentation-theme-jekyll/issues/31

**Comment by crandmck** [comment]
Fixed by above commit.  Thanks for reporting it!
