### ISSUE TITLE
Bad link in Defining-models.html to localhost

### ISSUE THREAD

**Issue by aharbis** [loopbackio/loopback.io#407]
## URL of the page 

https://loopback.io/doc/en/lb3/Defining-models.html

## Nature of the issue 

Bad link on this line to `localhost`:

>Once you've created a model, you can [customize it](Customizing-models.html) to suit your needs, and also add [data validation](Validating-model-data.html) and create [relationships among models](http://localhost:4001/doc/en/lb3/Creating-model-relations.html).

`relationships among models` --> `http://localhost:4001/doc/en/lb3/Creating-model-relations.html`

## Expected behavior

`relationships among models` should link to: `Creating-model-relations.html`

## Actual behavior

`relationships among models` links to: http://localhost:4001/doc/en/lb3/Creating-model-relations.html

## Suggested resolution

Edit the mentioned line to instead be:

Markdown:
>Once you've created a model, you can [customize it](Customizing-models.html) to suit your needs, and also add [data validation](Validating-model-data.html) and create [relationships among models](Creating-model-relations.html).

Raw:

    Once you've created a model, you can [customize it](Customizing-models.html) to suit your needs, and also add [data validation](Validating-model-data.html) and create [relationships among models](Creating-model-relations.html).

**Comment by crandmck** [comment]
@aharbis Thanks for catching...
Fixed with 6cd90ec
