### ISSUE TITLE
Small update relations tutorial

### ISSUE THREAD

**Issue by atherdon** [loopbackio/loopback.io#414]
## URL of the page 

http://loopback.io/doc/en/lb3/Tutorial-model-relations.html#create-model-relations

## Nature of the issue 

**slc** replace with **lb**

![tutorial model relations loopback documentation](https://user-images.githubusercontent.com/1469198/27898125-3c4548b2-61d9-11e7-94ab-ad20b9b7694e.png)

**Comment by crandmck** [comment]
Thanks for the suggestion, and good catch!  

To change this, please open a PR against https://github.com/strongloop/loopback-example-relations/blob/master/README.md.  The docs page is created from that README, as explained in http://loopback.io/doc/en/contrib/Including-READMEs.html.

**Comment by atherdon** [comment]
Ok, it's done @crandmck 
I created PR: https://github.com/strongloop/loopback-example-relations/pull/50
Will close this issue
