### ISSUE TITLE
Feature Request: lb schema create/update/delete/migrate

### ISSUE THREAD

**Issue by andreas83** [loopbackio/loopback.io#427]
i wonder why the model generator don't create the db schema afterwards, feels pretty obvious... 
also I miss some important cli commands like 
lb schema create,update,delete,migrate 

If this is not the right place to ask features request, please point me to the right location.

thx in advanced.

andreas

**Comment by crandmck** [comment]
@andreas83 Feature requests should go in https://github.com/strongloop/loopback.
This repo is only for documentation and issues related to docs.
