### ISSUE TITLE
New design for overview pages

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#430]
These are the top-level "overview" pages:
- [Home page](http://loopback.io/)
- [Getting Started](http://loopback.io/getting-started/)
- [Examples](http://loopback.io/examples)
- [Resources](http://loopback.io/resources)
- [Contributing](http://loopback.io/contributing)

![loopback io 1](https://user-images.githubusercontent.com/2925364/28937761-bf0a2664-7840-11e7-80b6-e141a31987fd.png)

**Comment by dhmlau** [comment]
Closing in favor of https://github.com/strongloop/loopback-next/issues/817
