### ISSUE TITLE
LoopBack logo - possible changes for lb-next

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#431]
Moved from #429.  Comment from @DaveYVR:
 
Loopback logos are below. If we do have a budget to change this, it would be great to streamline / update so it maintains a familiar feel rather than starting from scratch.
![loopback-logo-sm](https://user-images.githubusercontent.com/3076411/28938244-542e981e-7842-11e7-8383-bc8d2d13555d.png)
![loopback-logo-sm](https://user-images.githubusercontent.com/3076411/28938245-54362476-7842-11e7-8efe-cffca4ca2170.png)

![loopback-hero](https://user-images.githubusercontent.com/3076411/28938409-d06be364-7842-11e7-9e57-965a5ded6df8.png)

From @crandmck:
> Yeah, perhaps just change from green to blue color scheme, rather than a complete redesign?

From @hacksparrow:
> Let's keep the logo change consideration towards the end.

**Comment by dhmlau** [comment]
Closing this in favor of https://github.com/strongloop/loopback-next/issues/189
