### ISSUE TITLE
extend operational hook examples

### ISSUE THREAD

**Issue by atherdon** [loopbackio/loopback.io#434]
## URL of the page 
https://loopback.io/doc/en/lb3/Operation-hooks.html#before-delete
This section don't have an examples, that suits to situation when you want to change things in related models (simple version of 'cascade' delete).

## Suggested resolution
I propose to extend this section with example from [link](https://stackoverflow.com/questions/28607543/how-to-access-the-modal-instances-that-will-be-deleted-in-the-before-delete)
I think this will help other researches. For me it was very helpful

Thanks

**Comment by crandmck** [comment]
Yes, please open a pull request.  I think an example of a cascading delete would be great here.

**Comment by crandmck** [comment]
@atherdon ping...?

**Comment by lancedouglas1** [comment]
Submitted a PR with a simple "see also" link: https://github.com/strongloop/loopback.io/pull/570
