### ISSUE TITLE
typo in Customizing models page

### ISSUE THREAD

**Issue by aharbis** [loopbackio/loopback.io#440]
## URL of the page 

https://loopback.io/doc/en/lb2/Customizing-models.html

## Nature of the issue 

Typo in the following line (79):
>For example, to define a model called `MyModel` that extends from a custom model you defined called `mMyBaseModel`,

## Expected behavior

Line most likely was meant to be:
>For example, to define a model called `MyModel` that extends from a custom model you defined called `MyBaseModel`,

Note the defined base model's name is `MyBaseModel` not `mMyBaseModel`.

## Actual behavior

>For example, to define a model called `MyModel` that extends from a custom model you defined called `mMyBaseModel`,

## Suggested resolution

Change the line to:
```
For example, to define a model called `MyModel` that extends from a custom model you defined called `MyBaseModel`,
```

**Comment by crandmck** [comment]
Thanks @aharbis 
Good catch!
