### ISSUE TITLE
loopback:export-api-def hangs

### ISSUE THREAD

**Issue by dvelasquez** [loopbackio/loopback.io#443]
## URL of the page 

http://loopback.io/doc/en/lb3/API-definition-generator.html

(Source is https://github.com/strongloop/loopback.io/blob/gh-pages/pages/en/lb2/API-definition-generator.md).

## Nature of the issue 

Whenever im generating the definition, the cli hangs and never finish execution.
command: slc loopback:export-api-def --json -o client/models.json

File exported seems good.

## Expected behavior

CLI should close after generating the export.

## Actual behavior

CLI stay waiting. This happens when i use the -o option or not.

## Suggested resolution

Check if task is finish?

**Comment by crandmck** [comment]
I don't believe this is a doc issue, so moved to https://github.com/strongloop/loopback-cli/issues/53.
