### ISSUE TITLE
Broken link on Operation hooks page

### ISSUE THREAD

**Issue by aharbis** [loopbackio/loopback.io#444]
## URL of the page 

http://loopback.io/doc/en/lb3/Operation-hooks.html

## Nature of the issue 

In the `before save` section, there's a link in the below line which is broken:

>`currentInstance` - the instance being affected, see **Triggering with prototype.updateAttributes** below.

This links to: http://loopback.io/doc/en/lb3/Operation-hooks-version-3.0-.html

## Expected behavior

Link should not be broken.

## Actual behavior

Link is broken.

## Suggested resolution

I looked through the page, but I'm not entirely sure where it would be expecting to point to. Maybe the content was moved to another page somewhere?

**Comment by crandmck** [comment]
Fixed with 5ab8d74346928f0a876db5d75343c1d898f8b4fc.
Thanks for catching!
