### ISSUE TITLE
sidebar over extends into page content

### ISSUE THREAD

**Issue by damache** [loopbackio/loopback.io#455]
## URL of the page 

If applicable.

## Nature of the issue 
the sidebar overlaps the page content.  looks like pr #451 caused it.

## Expected behavior

What did you expect to happen?

## Actual behavior

What actually happenend, with steps to reproduce (if applicable).

## Suggested resolution

How do you think this should be resolved (optional).

**Comment by crandmck** [comment]
@damache I don't see this... Can you please provide an example/screenshot or steps-to-reproduce?
You may need to do a hard refresh to ensure that all the CSS files are being reloaded.

**Comment by crandmck** [comment]
nm, just saw your comment on https://github.com/strongloop/loopback.io/pull/451.  Will see if fixing the error you identify corrects it.

**Comment by damache** [comment]
![screenshot from 2017-09-12 14-51-03](https://user-images.githubusercontent.com/11265811/30345207-d8d08dc4-97c9-11e7-935d-dcd529991c20.png)


I'm in FF, the IBM version

**Comment by crandmck** [comment]
I tried it with IBM/FF 52.3.0 (64-bit on MacOS) and it lays out correctly for me (I usually use Chrome):
https://screencast.com/t/7proxZjIjh

Perhaps try clearing your cache?

**Comment by damache** [comment]
doesn't fix it @crandmck .  If I zoom to 90% it renders properly.

**Comment by CaptainHypertext** [comment]
This happens for me too, I'm using Chrome on a Windows 10 desktop, full screen.  I keep having to inspect element and reduce the column width to 15%.  For me, zooming to 90% doesn't fix it.

**Comment by crandmck** [comment]
Sorry about this, guys.  I'm still having a hard time reproducing it. Let me try when I get back to my office.

@christophherr any ideas?

**Comment by CaptainHypertext** [comment]
I've got a 1920 x 1080 monitor.  I notice that it only starts to happen when the window width gets to be above 1630px or so.  If I shrink the window width a bit, it looks better.

Happens in Edge too.

**Comment by crandmck** [comment]
OK, I remember now: https://github.com/strongloop/loopback.io/pull/451#issuecomment-329256127  Its happens for me in FF, but not Chrome.

So, there should be a way to address this "super wide window" situation...Someone who knows Bootstrap/CSS could probably fix it easily.  Unfortunately, I don't.... Anyone want to take a stab at it?

**Comment by christophherr** [comment]
@crandmck @CaptainHypertext Could you give the media queries in  https://github.com/strongloop/loopback.io/pull/451#issuecomment-329009405
a try? I don't have a 1920x1080 monitor to test.

**Comment by crandmck** [comment]
Thanks @christophherr I forgot/overlooked that!

It fixed the problem for me, but it would be great if someone else could test as well.  See [wide-window-fix](https://github.com/strongloop/loopback.io/tree/wide-window-fix) branch.  

@CaptainHypertext @damache want to give it a try?

**Comment by CaptainHypertext** [comment]
@crandmck Looks good on my end

**Comment by crandmck** [comment]
AFAICT #472 fixed this.  
If it still occurs, please reopen with details.

**Comment by damache** [comment]
sorry missed the email, was out sick last week.  just checked and it renders properly.  good job.
