### ISSUE TITLE
Problems with liquid include parameters containing non-Western characters

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#47]
I ran into a roadblock working on #37.  Jekyll/Liquid generates an error when processing includes with non-Western parameter values, e.g. 

```
{% include important.html content="
LoopBackがどのように動くかを理解するには**まずこのページをお読みください。次に、LoopBack
アプリケーションを作成するための基本的な紹介として [Getting started with LoopBack]
(/doc/{{page.lang}}/lb2/Getting-started-with-LoopBack.html)
を参照してください。" %}
```

The error is:

```
Liquid Exception: Invalid syntax for include tag. File contains invalid characters or sequences: 
important.html content=" LoopBackがどのように動くかを理解するには**まずこのページをお読みく
ださい。次に、LoopBackアプリケーションを作成するための基本的な紹介として [Getting started 
with LoopBack](/doc/ja/lb2/Getting-started-with-LoopBack.html) Valid syntax: {% include file.ext 
param='value' param2='value' %} in pages/ja/lb2/LoopBack-core-concepts.md
```

The English content makes extensive use of Liquid includes (with parameters) for [alerts](http://loopback.io/doc/en/contrib/alerts.html) and numerous other things.  So we need to resolve this or find a workaround, otherwise it's going to be much more difficult to provide translations of the docs.

**Comment by crandmck** [comment]
@Setogit @eddiemonge @cfjedimaster @joesepi  Would appreciate any help based on your Jekyll experience.  To repro, just copy/paste above into any page in the repo and then follow instructions in the README... Thanks!

**Comment by joesepi** [comment]
I think this is an issue with Liquid. This may be related? https://github.com/Shopify/liquid/issues/31

I'm on my phone so I am not able to test.

**Comment by crandmck** [comment]
Thanks @joesepi This may indeed be the source of the issue. Need to see if we can come up with a workaround, or if we're just hosed. :-(

**Comment by crandmck** [comment]
OK, it turns out that the issue is the liquid variable `{{page.lang}}` in the include parameter text, not the Chinese characters.  Doh!

The good news is that we can move forward with localization plans.
