### ISSUE TITLE
Create documentation or write article or improve doc on Change and Checkpoint

### ISSUE THREAD

**Issue by monster910** [loopbackio/loopback.io#482]
## URL of the page 

Not applicable

## Nature of the issue 

Lack of documentation of  major models when using cli 'lb model'

## Expected behavior

Better documentation about the use of the base models and why they exist. 

## Actual behavior

Not applicable.

## Suggested resolution

Write some more doc in the tutorial or document the classes better directly in API Docs.

**Comment by crandmck** [comment]
Have you read [Synchronization](https://loopback.io/doc/en/lb2/Synchronization.html), particular the [Understanding Replication](https://loopback.io/doc/en/lb2/Synchronization.html#understanding-replication) section?  It explains the Checkpoint and Change models.

The [loopback-example-offline-sync tutorial](https://loopback.io/doc/en/lb2/Tutorial-Offline-Synchronization.html) also provides some relevant info and examples.  

If these are not sufficient, could you please be more specific about what you'd want added?
