### ISSUE TITLE
fix unsafe scripts warning

### ISSUE THREAD

**Issue by buokae** [loopbackio/loopback.io#485]
## URL of the page 

For instance: https://loopback.io/doc/en/lb2/Creating-models.html but it happens site wide.

## Nature of the issue 

The site generates an error in Chrome: "This page is trying to load scripts from an unauthenticated source". It then displays without styling.

## Expected behavior

A well displayed page.

## Actual behavior

A not so well displayed page.

## Suggested resolution

Something with https and urls and script sources needs to be fixed.

**Comment by buokae** [comment]
Another suggested resolution is to make a site wide search engine.

**Comment by crandmck** [comment]
I checked in a change this morning that should fix it.  Currently, the page displays fine for me, and there's nothing in Chrome dev console either.

Please have another look and see if this still happens for you.

**Comment by buokae** [comment]
That fixed it form me too, everything displays fine now.
