### ISSUE TITLE
Global vs local install of TypeScript

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#509]
@bajtos @raymondfeng @dhmlau Please let me know your preference...

From https://github.com/strongloop/loopback.io/pull/505#issuecomment-340767687:

> ...let's install both ts-node and typescript locally. Polluting global scripts is an anti-pattern - what if somebody has an existing front-end project that requires an older version of TypeScript? There is no way to globally install two versions of typescript (one for their legacy front-end and another for LoopBack Next).

While I understand the reasoning behind this approach, I can see two issues:
- [TypeScript docs](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html)  and [README](https://www.npmjs.com/package/typescript) say to install it globally (with `-g`).  This may be confusing to users (who may be new to TypeScript).  Whose instructions do they follow?  
- The npm docs say to [install CLI tools globally](https://docs.npmjs.com/getting-started/installing-npm-packages-globally):  "...If you want to use [...] a command line tool, something like the grunt CLI, then you want to install it globally."
While TypeScript is a "library", it also provides the `tsc` CLI.   If you don't install it globally, then you can't use the `tsc` command; for example, Getting started currently has the user do `tsc --init` to create a new `tsconfig.json` file.  We can work around this by adding `"tsc": "./node_modules/typescript/bin/tsc",` to the `scripts` property in `package.json` then say to do `npm run tsc ..` instead.  IMHO that's a bit hacky; also to use any CLI options, you have to do `npm run tsc -- -<option>`.

Would it make sense to install `typescript` BOTH globally and locally?  That would enable them to use the `tsc` CLI without a hacky workaround.  And the project dep would override the global installation which ensures the project always uses the correct version. Or could this approach lead to other potential problems?

And do we need to use the `tsc` CLI?  Perhaps we can just avoid the issue by not having folks use it.  Instead of creating `tsconfig.json` with `tsc init`, we can tell them to just copy/paste the file...?

**Comment by dhmlau** [comment]
Here are my thoughts: 

> Would it make sense to install typescript BOTH globally and locally?

I don't think it make sense to tell the users to install typescript globally and locally.  
If installing globally is anti-pattern as @bajtos mentioned, perhaps we can recommend the users to do it locally?  At least that's our recommendation to our users who first install typescript because of loopback4?  Also, setting typescript as devDependencies will make typescript to be installed locally anyway. 

> And do we need to use the tsc CLI? 

`tsc` is used to transpile the code.  If `ts-node` is not something we recommend, we might want to remove any reference in our docs?  In our example repos, I believe we mostly use ` "start": "tsc && node ."` to transpile the typescript and start the application.

**Comment by raymondfeng** [comment]
I wonder if we should promote https://github.com/strongloop/loopback-next/tree/master/packages/build. 

See https://github.com/strongloop/loopback4-example-getting-started/blob/master/package.json#L10 for an example.

Please note that `@loopback/build` already has dependency on typescript. It first tries to use the one from the project and fall back to its own dependency.

I think the bottom line is that we don't need ts-node. We can use `tsc` or `lb-tsc` and `node .`

**Comment by crandmck** [comment]
OK, I removed `ts-node` from the process altogether, so now you compile the TypeScript with `./node_modules/typescript/bin/tsc` and run it with `node index.js` (I gave user the choice of entering those commands directly or putting them in `package.json`.  

Since the user creates the JS and TS code in the same project, I decided to use `app.js` for the main JS program file, so it doesn't get over-written when you compile `index.ts` later on.  I made a few other small changes, and ran through the procedure to ensure it works.

I was going to do this in a PR, but accidentally committed it mid-way through, so at this point it's live:
- http://loopback.io/doc/en/lb4/Installation.html
- http://loopback.io/doc/en/lb4/Getting-started.html

I can modify right away based on feedback.  @raymondfeng @dhmlau 

Before beta release, we may want to redo this anyway to use the "new" CLI instead.

**Comment by raymondfeng** [comment]
TypeScript should be a `devDependency`. Use `npm i typescript --save-dev`.

**Comment by dhmlau** [comment]
In http://loopback.io/doc/en/lb4/Installation.html#install-loopback-core-package, since it's a devDependency, the snippet should look like:
```
"devDependencies": {
  "@loopback/core": "^4.0.0-alpha.16",
  "typescript": "^2.5.3"
}
```

**Comment by crandmck** [comment]
OK, but just to clarify, Raymond said @loopback/core should be regular (not dev) dependency.

**Comment by crandmck** [comment]
Updated Installation and GS again to make TypeScript a dev dep. 

It occurred to me that we don't really need to do that for the JavaScript-based project, but I left it as a first step for either JS or TS devs.

**Comment by crandmck** [comment]
I'm going to close this for now.  If we want to change the procedure to use `@loopback/build`, suggest we open a new issue.
