### ISSUE TITLE
docs: missing content Preparing your API for consumption

### ISSUE THREAD

**Issue by bschrammIBM** [loopbackio/loopback.io#519]
## http://loopback.io/doc/en/lb4/Thinking-in-LoopBack.html#preparing-your-api-for-consumption

Need to provide content for this topic or indicated that it is not available for beta.

**Comment by dhmlau** [comment]
That's done through https://github.com/strongloop/loopback.io/pull/536. 
Here is the doc page: http://loopback.io/doc/en/lb4/Preparing-the-API-for-consumption.html

Closing it. Thanks.
