### ISSUE TITLE
Replace navigation widget

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#52]
The [navgoco](https://github.com/tefra/navgoco) JavaScript nav widget has a number of limitations and issues, and we probably should just replace it with something else.

For the most part, the server-side part that turns the [YAML sidebar file](https://github.com/strongloop/loopback.io/blob/gh-pages/_data/sidebars/lb2_sidebar.yml) into an unordered list is working OK.  One exception is that it doesn't allow 2nd-level items to have a URL, e.g. [Creating model relations](http://127.0.0.1:4001/doc/en/lb2/Creating-model-relations.html) is a container but is not linked to an article.  

At a minimum, it must:
- Create the nav from an HTML unordered list.
- Be responsive and work with Bootstrap.
- Be easy to change the display & make it look like we want.

There are dozens of possibilities, but https://www.jstree.com is a good candidate.  See also http://1stwebdesigner.com/jquery-menu/ for a list of other possibilities.

**Comment by Sequoia** [comment]
Looking into this

**Comment by Sequoia** [comment]
So if I understand you correctly: when someone clicks on a 2nd level nav "container," they should be sent to another page. I'll work with that assumption, please let me know if I'm wrong here

**Comment by Sequoia** [comment]
~~Thought: If we're doing a page reload on every nav click, why are we using JS at all?~~

Oh I see, there are two possible types of click on any tree container:
1. Click **title** 👉  navigate to new page
2. Click **arrow** 👉  open that tree level

**Comment by crandmck** [comment]
> Oh I see, there are two possible types of click on any tree container

Yes, that's how it works now, but IMO it's not a great UX.  Both options are not always obvious.  I think it would be better to always open the tree and (if there's a link) open it as well.  This is how the Confluence navigation worked (except that every item in the nav tree was _always_ linked).

**Comment by crandmck** [comment]
@Sequoia I pinged you via Google, so we can start a hangout.

**Comment by Sequoia** [comment]
recommend closing this with additional bugs/issues tracked on other tickets e.g. #55
