### ISSUE TITLE
docs: missing content - Calling other APIs and web services

### ISSUE THREAD

**Issue by bschrammIBM** [loopbackio/loopback.io#520]
http://loopback.io/doc/en/lb4/Calling-other-APIs-and-web-services.html

Your API implementation often needs to interact with REST APIs, SOAP Web Services or other forms of APIs.
How to:
•	Set up a Service
•	Use services with controllers
•	Reuse models between services and controllers
 Work-in-progress: This section is not yet complete.

**Comment by dhmlau** [comment]
related to: https://github.com/strongloop/loopback.io/pull/641

**Comment by dhmlau** [comment]
It's been updated with relevant information.  Closing this issue.
