### ISSUE TITLE
The links to scripts are going nowhere

### ISSUE THREAD

**Issue by simoroshka** [loopbackio/loopback.io#541]
## URL of the page 

http://loopback.io/doc/en/lb3/Connecting-to-PostgreSQL.html

## Nature of the issue 

If I want to see the contents of the model.json and the automigrate script, I get to a 404 page.

**Comment by dhmlau** [comment]
@simoroshka , that's interesting.  I just tried it with Chrome and Firefox, the link is working.  
If it still doesn't work for you, could you please provide with OS with version, and the browser you're using?  thanks.

**Comment by simoroshka** [comment]
I am on Mac Sierra 10.12.6, Chrome browser 61.0.3163.10. 


<img width="727" alt="screen shot 2017-11-18 at 13 47 51" src="https://user-images.githubusercontent.com/7287215/32979966-26e484bc-cc67-11e7-81cf-9fb5ce84c85f.png">

<img width="562" alt="screen shot 2017-11-18 at 13 48 05" src="https://user-images.githubusercontent.com/7287215/32979965-26c744d8-cc67-11e7-9f1f-9e59f4fd545c.png">

**Comment by dhmlau** [comment]
@simoroshka, I thought you have problem accessing the Connecting-to-PostgreSQL.html page.  Sorry about that. 
This page is actually coming from the `README.md` in the `loopback-example-database` repo, therefore, the path should be relative to that repo.  i.e. 
https://github.com/strongloop/loopback-example-database/blob/master/common/models/account.js
https://github.com/strongloop/loopback-example-database/blob/master/bin/automigrate.js

@bschrammIBM, any thoughts how we can fix it?  Thanks.

**Comment by bschrammIBM** [comment]
I suggest accessing the script from the above links provided by @dhmlau for now. 
There are some web site production issues I need to sort through to figure out how to fix the links on http://loopback.io/doc/en/lb3/Connecting-to-PostgreSQL.html.
