### ISSUE TITLE
 using middleware.json in loopback 4 

### ISSUE THREAD

**Issue by Debanjan123** [loopbackio/loopback.io#550]
In loopback 4 ,how do we use to host folder with the same port.In version 3 i use 
 "files": {
    "loopback#static": {
      "params": "$!../client"
    }
  },
to host client folder.
Now is there any option available to host client folder

**Comment by shimks** [comment]
Hi @Debanjan123, the feature for LoopBack's REST component to support static file hosting is currently being planned, and you can keep a track of its progress in this issue: https://github.com/strongloop/loopback-next/issues/691. Thanks for letting us know that users are actively looking for this feature. I'll be closing this issue for now.
