### ISSUE TITLE
possible documentation  improvement

### ISSUE THREAD

**Issue by drlukeangel** [loopbackio/loopback.io#576]
## URL of the page 

If applicable.

## Nature of the issue 
documentation improvement
Is this an issue with the layout/behavior/UX of the site or a problem with missing/inaccurate documentation content?

**documentation content**

  

## Expected behavior
on the page: 
https://github.com/strongloop/loopback.io/blob/gh-pages/pages/en/lb3/Introducing-the-Coffee-Shop-Reviews-app.md

issue 1:
for reviewers --> 
Base class: Use the down-arrow key to select User.

**Could use some context here around what this means.** 

issue 2: 
Using the API explorer you can't login via the user/login method

**Based on the explorer interface  i would think that i could use the http://localhost:3000/explorer/#!/User/User_login to login, but this is not the case you need use http://localhost:3002/explorer/#!/Reviewer/Reviewer_login. 
To me this is not intuitive. Either remove the user object from the api explorer or remove the login method from the reviewer object.**

**
the user/login doesn't include the required json object that needs to be submitted in the swagger definition. this should as well be updated to be {email: "theUserNameOfTheUser@username.com", password: "thePasswordOfTheUser"}
**

**Comment by bschrammIBM** [comment]
Thank you for your issue. Our technical team will review this shortly.

**Comment by dhmlau** [comment]
@drlukeangel, thanks for your comments.  Would you mind to submit a PR?  Thanks!
