### ISSUE TITLE
Broken link on https://loopback.io/doc/en/lb4/Decorators.html

### ISSUE THREAD

**Issue by bschrammIBM** [loopbackio/loopback.io#605]
## URL of the page 

https://loopback.io/doc/en/lb4/Decorators.html

## Nature of the issue 
There is a broken link to: https://loopback.io/lb3/Model-definition-JSON-file.html 
The link is in italics below.

Model Decorator
Syntax: @model(definition?: ModelDefinitionSyntax)

Model decorator is a Class decorator. In LoopBack 4, we inherit the model definition format from LoopBack 3, you can find it in *Model definition JSON* file. For usage examples, see Define Models

## Expected behavior

Link would open the correct page

## Actual behavior

page not found

## Suggested resolution

Is there another url or does the topic not exist?
Need to change link or create the page.

**Comment by bschrammIBM** [comment]
I found the topic in LB3, this is the correct url: https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html
Need to check why the link doesn't work
The url needs to updated. Wrong url: https://loopback.io/lb3/Model-definition-JSON-file.html

**Comment by shimks** [comment]
Issue is solved with #606
