### ISSUE TITLE
Add warning about using other form parsers with LoopBack

### ISSUE THREAD

**Issue by hacksparrow** [loopbackio/loopback.io#661]
## URL of the page 

http://loopback.io/doc/en/lb3/Storage-component.html

**Comment by hacksparrow** [comment]
Changes not reflected on website, re-opening.

**Comment by dhmlau** [comment]
@hacksparrow , are the changes propagated properly now?

**Comment by hacksparrow** [comment]
Yes

**Comment by dhmlau** [comment]
Closing it as resolved.
