### ISSUE TITLE
Create Issue Template

### ISSUE THREAD

**Issue by Sequoia** [loopbackio/loopback.io#67]
[Issue templates](https://github.com/blog/2111-issue-and-pull-request-templates)
## Some possible info to request (for this _docs_ repo)

Maybe not all of this...
1. URL
2. Site bug or Content bug/errata
3. What was the content problem?
   - missing docs?
   - inaccurate docs?
4. What question were you looking for an answer for in the docs?
5. What change would you like to see? _(what would "resolve" this doc issue?)_

**Comment by crandmck** [comment]
Hey @Sequoia I went ahead and created https://github.com/strongloop/loopback.io/blob/gh-pages/ISSUE_TEMPLATE.md.  In general, I'd like to keep issues in this repo primarily for the layout/behavior of the doc site itself; and use other repos (e.g. `loopback`) for issues around doc content.  That being said, I expect people will open doc content issues here anyway, and I don't think it's that big of a deal.

I'm going to close this; we can iterate on the issue template as we go.  Thanks for the suggestion!
