### ISSUE TITLE
The demo.strongloop.com link is down

### ISSUE THREAD

**Issue by carloslfu** [loopbackio/loopback.io#673]
## URL of the page 

https://github.com/strongloop/loopback.io/blob/gh-pages/pages/en/lb3/Create-new-data-source.md

Line 57

## Nature of the issue 

The demo.strongloop.com link is down

**Comment by dhmlau** [comment]
@carloslfu , thanks for reporting this issue.  Given that we can easily start a mongodb docker image, I think it's better to change this documentation to ask the user to use their own mongodb database (in docker container or not). 

Would you be interested to submit a PR to fix this?  Some useful info can be found here: https://github.com/strongloop/loopback-connector-mongodb/blob/master/README.md

**Comment by carloslfu** [comment]
Hi @dhmlau. Of course, I will submit a PR fixing this. Thanks for the info.

**Comment by adrianhill102** [comment]
This link is still down, who can fix this?
