### ISSUE TITLE
Customer request regarding kafka connector

### ISSUE THREAD

**Issue by bschrammIBM** [loopbackio/loopback.io#678]
Customer wants to know which connector to use for Kafka:
"Which npm package should I use: "loopback-connector-kafka" or "kafka-node"?"
In LB 2.0 docs, we list loopback-connector-kafka (see https://loopback.io/doc/en/lb2/Community-connectors.html). But we do not list a kafka connector in the LB 3.0 docs.

Shall I tell the customer to use  loopback-connector-kafka?
Or are we not recommending a Kafka connector in 3.0?

**Comment by jannyHou** [comment]
@bschrammIBM "loopback-connector-kafka" is a connector maintained by community, loopback team doesn't officially support it, we could do best effort help.
"kafka-node" is the node driver for Kafka, has nothing to do the loopback REST model operations, user need to write the underneath logic as the connector to implement those loopback REST operations.

**Comment by bschrammIBM** [comment]
Thanks I will tell them to try loopback-connector-kafka, but that it is a community maintained connector. Closing
