### ISSUE TITLE
List of connectors that support transaction is not complete

### ISSUE THREAD

**Issue by dhmlau** [loopbackio/loopback.io#686]
## URL of the page 
https://loopback.io/doc/en/lb3/Using-database-transactions.html

## Nature of the issue 
The above link shows only MySQL, Prostgreql, MSSQL and Oracle connectors have transaction support.  However, this list is not complete, at least DB2 connector support transactions. 

## Expected behavior
The documentation shows a complete list of connectors that support transactions. 

## Acceptance Criteria
- [ ] Go through each connector we support, i.e. from [available-connectors.json]( https://github.com/strongloop/loopback-workspace/blob/master/available-connectors.json) where `"supportedByStrongLoop": true`:
   - see if there is a `beginTransaction` function in `transaction.js`.  
   - if it exists, that means the connector support transaction.
- [ ] update the doc https://loopback.io/doc/en/lb3/Using-database-transactions.html to reflect the information. 

~**Question**
@strongloop/lb-next-dev, I'd like to make sure if a connector  has `beginTransaction` function in `transaction.js`, we can safely assume that it supports transaction.~ Answered below by @jannyHou

**Comment by jannyHou** [comment]
@dhmlau 
> if a connector has beginTransaction function in transaction.js, we can safely assume that it supports transaction

From my experience of SQL connectors, yes we can safely assume it, usually the transaction related methods are written in a single file `transaction.js`, like the one in dashdb connector https://github.com/strongloop/loopback-connector-dashdb/blob/master/lib/transaction.js

We also have a bunch of db2 connectors for other platforms: 

- loopback-connector-db2
- loopback-connector-dashdb
- loopback-connector-db2iseries
- loopback-connector-db2z
- loopback-connector-informix

support transaction.

**Comment by dhmlau** [comment]
thanks @jannyHou. What about non-sql connectors?

**Comment by jannyHou** [comment]
@dhmlau I am not aware of any non-sql connectors has transaction, at least mongodb, cloudant, cassandra doesn't have it. 

We can go through all the connectors list in https://github.com/strongloop/loopback-workspace/blob/master/available-connectors.json in case we miss some.

**Comment by bschrammIBM** [comment]
I have added the following links to database connectors per @jannyHou input:
loopback-connector-db2
loopback-connector-dashdb
loopback-connector-db2iseries
loopback-connector-db2z
loopback-connector-informix 

I looked through the loopback-connector-* repos and did not find any other database connectors with a transaction.js file. 

Suggest that this can be closed.

**Comment by dhmlau** [comment]
@bschrammIBM , thanks for looking into it.  Where did you make the changes?  When i go to the database transaction page (https://loopback.io/doc/en/lb3/Using-database-transactions.html), it still doesn't have the connectors you've listed above.

**Comment by bschrammIBM** [comment]
It's there now on the page https://loopback.io/doc/en/lb3/Using-database-transactions.html

**Comment by dhmlau** [comment]
Closing as resolved.
