### ISSUE TITLE
Updated 3.20.0 apidocs is missing PersistedModel documentation

### ISSUE THREAD

**Issue by aharbis** [loopbackio/loopback.io#706]
## URL of the page 

http://apidocs.loopback.io/loopback/v/3.20.0/

## Nature of the issue 

It appears that in the update from version `3.19.3` to `3.20.0` the documentation for the class `PersistedModel` is missing.

## Expected behavior

The `PersistedModel` class documentation should exist at the above URL.

## Actual behavior

The `PersistedModel` class documentation is missing from the above URL.

**Comment by virkt25** [comment]
Fixed.
