### ISSUE TITLE
Update lb3 docs with zosconnectee

### ISSUE THREAD

**Issue by bschrammIBM** [loopbackio/loopback.io#708]
## URL of the page 

https://loopback.io/doc/en/lb3/Command-line-tools.html

## Nature of the issue 

Update the cli reference with zosconnectee https://github.com/strongloop/loopback-connector-zosconnectee#create-a-datasource

There may be other places in the docs that require updates to support zosconnectee command.

## Expected behavior

What did you expect to happen?

## Actual behavior

What actually happenend, with steps to reproduce (if applicable).

## Suggested resolution

How do you think this should be resolved (optional).

**Comment by bschrammIBM** [comment]
The files have been updated but for some reason the topic is not displayed on https://loopback.io/doc/en/lb3/index.html Will check back in case it is just a delay in the automated update.

**Comment by virkt25** [comment]
The reason for it failing is because the YAML added has Syntax error (extra spaces for `url` and `output`. As a result, the build fails and the site doesn't get updated. 

```
    - title: 'z/OS Connect Enterprise Edition connector'
        url: zOSconnectEE.html
        output: 'web, pdf'
```

vs. the correct output:

```
    - title: 'z/OS Connect Enterprise Edition connector'
      url: zOSconnectEE.html
      output: 'web, pdf'
```

**Comment by marioestradarosa** [comment]
FYI , I had VSCode prettier plugin making this type of indentation automatically. I had to add .yml at the end of the .prettierignore file .

**Comment by bschrammIBM** [comment]
The page has been added to the loopback.io doc site at
https://loopback.io/doc/en/lb3/zOSconnectEE.html
Closing
