### ISSUE TITLE
Documentation missing/outdated

### ISSUE THREAD

**Issue by hajdun** [loopbackio/loopback.io#713]
## URL of the page 
https://github.com/strongloop/loopback.io/blob/gh-pages/pages/en/lb3/Connecting-to-SOAP.md

## Nature of the issue 
Among others, the mentioned soap service (http://www.webservicex.net/periodictable.asmx) is NOT available. The example code based on this page is not working.

Worst of all is that the step-by-step guide did result in a not-working mess. 
Some of the plugins breaks the SOAP schema and it will not be able to send and receive SOAP messages.

Is this an issue with the layout/behavior/UX of the site or a problem with missing/inaccurate documentation content?
Both :( 

## Expected behavior

What did you expect to happen?
I expected this tutorial to work 
https://loopback.io/doc/en/lb3/Connecting-to-SOAP.html

## Actual behavior

Doc not helpful. Result (applied in my context) is 

soap:Client faultstring: Unmarshalling Error: unexpected element (uri:\"\", local:\"__cached Relations\").
 similar to thishttps://github.com/strongloop/loopback-connector-soap/issues/77

## Suggested resolution
Please fix documentation at least. Add a working service and working steps. Thanks!

**Comment by dhmlau** [comment]
@hajdun, sorry that we haven't had the chance to clean up the docs after the service in webservicex.net become unavailable.  Would you be interested in submitting a PR for fixing the docs?  

A community user helped us to fix the tests by using another web service: https://github.com/strongloop/loopback-connector-soap/blob/master/test/test.js.

**Comment by b-admike** [comment]
From @raymondfeng:
- Create and use a dockerized SOAP web service which can be used as a test bed for the example for the documentation page

**Comment by hajdun** [comment]
I cannot, that is a 3rd party. Here is a free SOAP API I found (also 3rd party): https://geoservices.tamu.edu/Services/Geocode/WebService/v04_01/Simple/SOAP/
