### ISSUE TITLE
Handling of AccessTokens when logging in from multiple browsers

### ISSUE THREAD

**Issue by JuergenSimon** [loopbackio/loopback.io#714]
I need some help in understanding how loopback handles AccessTokens. We have a setup where it's ok for the user to log in from multiple contexts / devices. They always log in with the same email/password combination. How is this handled in loopback? Will loopback create a new AccessToken each time? How does it handle re-use of AccessToken? Will this present a problem for us if we have to rely on each AccessToken to be unique per device/context?

**Comment by dhmlau** [comment]
@virkt25 ,  you were just looking at AccessToken related area.  Could you PTAL?  Thanks.

**Comment by virkt25** [comment]
LoopBack creates a new token for each `login()` request received. The tokens are stored in a new table (userId, accessToken, ttl). So it's possible for a user to be logged in from multiple devices with this approach. The same token isn't re-used AFAIK. Resetting a password will invalidate all previous tokens for the user. 

Hope this helps. If you have any more questions, feel free to ask.

**Comment by dhmlau** [comment]
Closing this issue as resolved.
