### ISSUE TITLE
REST connector example: broken links

### ISSUE THREAD

**Issue by bisonfoutu** [loopbackio/loopback.io#722]
## URL of the page 

https://loopback.io/doc/en/lb2/REST-connector-example.html

## Nature of the issue 

Broken links.

## Expected behavior

Multiple links should point to example source files on Github.

## Actual behavior

The links actually point to a deleted repository.

## Suggested resolution

Depending on the files having been moved or actually deleted, the links should be updated in the first case, or this documentation page should be reworked.

I later noticed that it concerns the docs for version 2.x, so it may be a deliberate choice, but as the docs are not marked as deprecated I believe it should still be usable.

**Comment by dhmlau** [comment]
@bushybuffalo , thanks for reporting this!  The example repo has been moved to this location: https://github.com/strongloop-community/loopback-example-connector.   Hope it will get you going before the docs is fixed.

In the meanwhile, would you be interested in submitting a PR to fix this?  Thanks.
