### ISSUE TITLE
Fix remote methods source property values documentation

### ISSUE THREAD

**Issue by bs85** [loopbackio/loopback.io#737]
## URL of the page 

https://loopback.io/doc/en/lb3/Remote-methods.html

## Nature of the issue 

In the "Using an object with a source property" section, it says " Note that query and path are aliases for form".

Looking at the code, all 3 have different behaviors. `form` picks from the request body, `query` from the query params, and `path` from both.

**Comment by gemyero** [comment]
@bs85 I have solved this and my PR is already merged
https://github.com/strongloop/loopback.io/pull/744

**Comment by bs85** [comment]
Cheers!
