### ISSUE TITLE
Error: The query object is too deep or circular

### ISSUE THREAD

**Issue by Archynet-GitHub** [loopbackio/loopback.io#759]
I've done a find query on a model and i get the error above. I get this error from a few days, before it works. The filter where is the following:

```js
      where: {
        and: [
          {venueId: venue}, whereCondition
        ]
      }
      ,
      include: ['openingSchedule', 'areas',
        {
          relation: 'categories',
          scope: {
            where: whereCondition,
            include: [
              {
                relation: 'subcategories'
              },
              sizeRelation,
              {
                relation: 'translations',
              }, 'openingSchedule',
              {
                relation: 'items',
                scope: {
                  where: whereCondition,
                  include: [
                    {
                      relation: 'sizes',
//                      scope: {
//                        include: [
//                          {
//                            relation: 'size',
//                            scope: {
//                              include: [
//                                {
//                                  relation: 'translations',
//                                }
//                              ]
//                            }
//                          }
//                        ]
//                      }
                    },
                    {
                      relation: 'options'
                    },
                    {
                      relation: 'allergens',
//                      scope: {
//                        include: [
//                          {
//                            relation: 'translations',
//                          }
//                        ]
//                      }
                    },
                    {
                      relation: 'translations',
                    },
                    {
                      relation: 'variations',
//                      scope: {
//                        include: [
//                          {
//                            relation: 'translations',
//                          }
//                        ]
//                      }
                    },
                    {
                      relation: 'itemVariations',
                    },
                    {
                      relation: 'ordertypesizes'
                    }
                  ]
                }
              },
              {
                relation: 'ordertypes'
              }
            ]
          }
        },
        {
          relation: 'translations',
        },
        {
          relation: 'ordertypes'
        },
        {
          relation: 'openingSchedule'
        },
        {
          relation: 'languages'
        },
        {
          relation: 'locationtypes'
        }
      ]
    }
```
Since before the same filter worked, i suppose that is an issue.

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/loopback-datasource-juggler/pull/1638#issuecomment-437407868

You should configure `maxDepthOfQuery` for the datasource or model settings.

**Comment by dhmlau** [comment]
Cross posting @raymondfeng's comment from https://github.com/strongloop/loopback-datasource-juggler/issues/1653#issuecomment-434750713: 
> Please use 3.26.0/4.2.0 and follow instructions at https://github.com/strongloop/loopback.io/blob/gh-pages/pages/en/lb3/Querying-data.md#sanitizing-filter-objects

**Comment by dhmlau** [comment]
Closing this issue as resolved. Thanks.

**Comment by Tyagi0502** [comment]
I've been facing QUERY_OBJECT_TOO_DEEP issue quite a lot recently. Specifically for a particular API. 

I had the maxDepthOfQuery set to default and it was working. Until suddenly it stoped working. I increased maxDepthOfQuery value to 64 and it worked for a few months and then it came up again. I increased maxDepthOfQuery to 64 and it went away for a couple of days and back it came.

Can you please tell me what exactly is this maxDepthOfQuery and how can it possibly change for an API which has not been altered.

**Comment by Tyagi0502** [comment]
> See [strongloop/loopback-datasource-juggler#1638 (comment)](https://github.com/strongloop/loopback-datasource-juggler/pull/1638#issuecomment-437407868)
> 
> You should configure `maxDepthOfQuery` for the datasource or model settings.

I've been facing QUERY_OBJECT_TOO_DEEP issue quite a lot recently. Specifically for a particular API.

I had the maxDepthOfQuery set to default and it was working. Until suddenly it stoped working. I increased maxDepthOfQuery value to 64 and it worked for a few months and then it came up again. I increased maxDepthOfQuery to 64 and it went away for a couple of days and back it came.

Can you please tell me what exactly is this maxDepthOfQuery and how can it possibly change for an API which has not been altered.
