### ISSUE TITLE
Static web pages can not be added

### ISSUE THREAD

**Issue by gbosetti** [loopbackio/loopback.io#762]
## URL of the page 

https://github.com/strongloop/loopback.io/blob/gh-pages/pages/en/lb3/Add-a-static-web-page.md

## Nature of the issue 

The provided example is not working.

## Expected behavior

To load a simple static html file

## Actual behavior

Error
404 There is no method to handle GET /
Error: There is no method to handle GET /
    at restUrlNotFound ...

## Suggested resolution

How do you think this should be resolved (optional).

**Comment by dhmlau** [comment]
@hacksparrow , could you please take a look? Thanks.

**Comment by hacksparrow** [comment]
@gbosetti I agree, the guide can be simpler and clearer.

Serving static files is actually very simple. You just need to keep your static files in the `client` directory and add the following to `middleware.json` file:

```js
  "files": {
    "loopback#static": {
      "params": "$!../client" 
    }
  },
```

@dhmlau I tried to rewrite the content, but it is a part of a series; cannot make edits without disruption, which will result in more work.
