### ISSUE TITLE
translation of files inside (_ includes/readmes )

### ISSUE THREAD

**Issue by jaimeneeves** [loopbackio/loopback.io#77]
How do I translate the files inside the folder (_ includes/readmes ) ?

**Comment by crandmck** [comment]
An excellent question.  

Here's a summary of how they are pulled into the repo: http://loopback.io/doc/en/contrib/Including-READMEs.html

I haven't come up with a good way to localize these yet.  I'll work on this, but in the meantime, you can do this:
- Find the file where the README is included, e.g. `Angular-example-app.md`.
- Delete the line that does include, e.g. `{% include readmes/loopback-example-angular.md %}`.
- Copy/paste the content of the README into it, and then translate that content.
- Delete `layout: readme` from the front matter.

This will work for the time being.  I'll try to establish a better procedure though; but this would probably involve adding translated READMEs to the other repos.

**Comment by crandmck** [comment]
Hi @dejaneves I'm going to close this.  Please let me know if you have questions or run into any other issues.  Thanks for helping us pioneer translations!
