### ISSUE TITLE
document link missing in integrate geo-coding service

### ISSUE THREAD

**Issue by nguyenjk** [loopbackio/loopback.io#774]
## URL of the page 
https://loopback.io/doc/en/lb4/todo-tutorial-geocoding-service.html
## Nature of the issue 
the link is broken: 
https://loopback.io/doc/en/lb4/Calling-other-APIs-and-web-services.md

## Expected behavior

can you correct the link or make it available ?

## Actual behavior

you should see the content

## Suggested resolution

the file permission or missing file should be updated

**Comment by dhmlau** [comment]
the link should be https://loopback.io/doc/en/lb4/Calling-other-APIs-and-web-services.html, instead of `.md`.  
Would you like to submit a PR?  It's coming from this file: https://github.com/strongloop/loopback-next/blob/master/docs/site/todo-tutorial-geocoding-service.md.

**Comment by dhmlau** [comment]
Closing as fixed.
