### ISSUE TITLE
Scrollbar position on new theme

### ISSUE THREAD

**Issue by Tyler-RCSD** [loopbackio/loopback.io#777]
## URL of the page 

https://loopback.io/doc/en/lb3/Defining-models.html

## Nature of the issue 

On screen widths larger than 1600 pixels the scrollbar overlaps the main content text.
![lb](https://user-images.githubusercontent.com/42674425/48778102-f5099f00-ec99-11e8-87d4-4a78921f3287.PNG)

## Suggested resolution

Revert theme or fix css.

**Comment by dhmlau** [comment]
@nabdelgadir, could you please take a look? thanks.

**Comment by dhmlau** [comment]
Should be fixed via #778. Could you please verify? Thanks.

**Comment by Tyler-RCSD** [comment]
Much better. Thank you!
