### ISSUE TITLE
Promote LB4 in loopback.io site

### ISSUE THREAD

**Issue by dhmlau** [loopbackio/loopback.io#786]
With LB4 being the current release and LB3 as LTS release, it would be great if LB4 shows up as a more prominent location in loopback.io web site. 

Discussed with @raymondfeng @bajtos, we're thinking along the line of [Node.js web site](https://nodejs.org/en/). See screen shot below: 

![screen shot 2018-12-12 at 1 21 38 pm](https://user-images.githubusercontent.com/25489897/49889916-b9817100-fe10-11e8-9e52-bc40c069da53.png)

## Acceptance Criteria
- [ ] in the main banner of loopback.io, shows 2 "buttons" - one for LB3 and one for LB4.  
  - LB4 button points to v4.loopback.io
  - possibly some text around when to use LB3 and when to use LB4, since there's some feature parity gap in LB4

cc @raymondfeng @bajtos 

@joesepi, this is originated from your comment.  Appreciate your input.  Thanks!

**Comment by joesepi** [comment]
I think this makes perfect sense. Perhaps have a short bit of text above the buttons highlighting v4 and that v3 is "LTS" or however you'd phrase that. I could potentially help with this work after the holidays. Thanks.
