### ISSUE TITLE
Doc incorrectly states Models do not inherit ACLs from their Base model

### ISSUE THREAD

**Issue by aharbis** [loopbackio/loopback.io#787]
## URL of the page 

https://loopback.io/doc/en/lb3/Managing-users.html#security-considerations

## Nature of the issue 

Unclear content.

## Expected behavior

Documentation on model inheritance and built-in ACLs should be clear.

## Actual behavior

This page has the following content:

>Since a model doesn’t inherit ACLs from its base model, you must define ACLs for the new custom model.

This appears to be incorrect from my discussion with @raymondfeng. I have also found lengthy discussion in https://github.com/strongloop/loopback/issues/2270 that seems to indicate the same.

## Suggested resolution

Documentation should be clarified to indicate what the expected behavior for inheriting a model with a built-in ACL is.

**Comment by aharbis** [comment]
I know LB3 is ending support next year, but this has been a pain-point for me when reviewing documentation and trying to build out our own "user" model architecture. Hopefully this is an easy clarification to make in the doc.

**Comment by dhmlau** [comment]
@aharbis, would you be interested in submitting a PR? Thanks.

**Comment by aharbis** [comment]
bump
