### ISSUE TITLE
3.x Getting Started part II - create new model incorrect instructions

### ISSUE THREAD

**Issue by phansw** [loopbackio/loopback.io#792]
## URL of the page 
https://loopback.io/doc/en/lb3/Create-new-models.html

## Nature of the issue 
Under the section 'Define the Reviewer model', instructions to create the base class states to 'Use the down-arrow key to select User'. Using version 3.24, the way to set the base class to 'User' is to select custom from the menu, and then manually typing in User.

## Suggested resolution

Update the docs to something like 'Use the down-arrow key to select (custom), and enter User.'

**Comment by dhmlau** [comment]
@phansw, thanks for pointing it out.  Would you like to submit a PR?  
In case you're new to submit PR to our repos, you can find some instructions in here: https://loopback.io/doc/en/contrib/doc-contrib.html.  Thanks.

**Comment by phansw** [comment]
Alright I'll submit a PR

**Comment by dhmlau** [comment]
Thanks for submitting PR https://github.com/strongloop/loopback.io/pull/793.
I just added some comments over there. Thanks.

**Comment by dhmlau** [comment]
Closing this issue as it doesn't seem to be a problem.  My finding and the discussion with @phansw are captured in https://github.com/strongloop/loopback.io/pull/793.
