### ISSUE TITLE
Incomplete Documentaion on how to use Cookies with LB3

### ISSUE THREAD

**Issue by gaurav21r** [loopbackio/loopback.io#796]
## URL of the page 

https://loopback.io/doc/en/lb3/Making-authenticated-requests.html

## Nature of the issue 

Missing Documentation

## Expected behavior

A complete example of how to use Loopback Authentication with Cookies

## Actual behavior

Current Documentation / Sample Code Repo does not solve this

## Suggested resolution

Please see https://github.com/strongloop/loopback/issues/2142#issuecomment-396938268

All that's required is this code to be present in the documentation.

**Comment by dhmlau** [comment]
@gaurav21r , would you like to submit a PR?  The corresponding file is https://github.com/strongloop/loopback.io/blob/gh-pages/pages/en/lb3/Making-authenticated-requests.md.

**Comment by gaurav21r** [comment]
Ok i'll try, will update here if im going ahead
