### ISSUE TITLE
Sidebar container items indented too far

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#80]
Sidebar container items are left-indented more than items that are not containers:
![sidebar-layout](https://cloud.githubusercontent.com/assets/2925364/19000695/d0c1ddb4-86f8-11e6-97ca-1adc3ee1d8f8.png)

The left-padding of these articles should be the same whether they are a container or not, because an item is at the same "level" in the hierarchy, regardless of whether it has children or not.  

So, in the example shown here, the **+** for "Validating model data" should align with the beginning of "Exposing models over REST"

(I need to remove the duplicate "Defining models" item which is a leftover from the old scheme, but that's another matter).

**Comment by Sequoia** [comment]
@crandmck What browser are you using?

**Comment by crandmck** [comment]
Chrome - Version 53.0.2785.116 (64-bit)

**Comment by Sequoia** [comment]
Does this revision look right?
![](https://i.imgur.com/5i3J3Tw.png)

I ended up changing the styles around some to remove take block display off the menu links. This made it easier to get everything to line up but means that the tree parent menu text will wrap directly below the `+`, and I'm not sure if that meets your requirements.

I'll look into another approach that preserves the block styles in the meantime.

**Comment by crandmck** [comment]
Yes, the alignment looks fine, but I'd like to keep the existing "highlighting" (blue rounded box) rather than what's shown above (bold, blue bar to left).

And, the text wrapping immediately below the "+" is not ideal; would be better to have the text wrap align with the beginning of the label if possible.

**Comment by Sequoia** [comment]
I've fixed the wrapping issue

![screen shot 2016-09-30 at 4 45 48 pm](https://cloud.githubusercontent.com/assets/317498/19006441/74fe6cb0-872d-11e6-90e7-ca185b174cd7.png)

I'll see about restoring the highlighting. The issue there was one of padding... anyway I'll see what I can do :)

**Comment by crandmck** [comment]
Cool, thanks!

**Comment by crandmck** [comment]
Fixed by #84
