### ISSUE TITLE
Search "sidebar" replacing with lb3

### ISSUE THREAD

**Issue by rahulrkr08** [loopbackio/loopback.io#808]
## URL of the page 

https://loopback.io/search/?q=rest&sidebar=lb4_sidebar

## Nature of the issue 

Re-searching from search page, replacing sidebar option to lb3 instead of lb4 and results are coming again from lb3.

## Expected behavior

Keep the state of sidebar as "lb4_sidebar"if it is in query.

**Comment by nabdelgadir** [comment]
Fixed via #815, thanks for the contribution!
