### ISSUE TITLE
lb-tsc: not found

### ISSUE THREAD

**Issue by ri8ika** [loopbackio/loopback.io#810]
When I'm trying to deploy my app in heroku. I get this log:

`lb-tsc: not found`

Please help me what can be a fix.

It's a loopback 4 application.

**Comment by raymondfeng** [comment]
Is `@loopback/build` a dev dependency in your module's package.json? If so, does `npm install` happen?

**Comment by bhojport** [comment]
Yes. It is there in dev dependency.

**Comment by ri8ika** [comment]
Yes. It's there in dev dependency.

**Comment by ri8ika** [comment]
Ah, thanks. I need to do `npm install`.
Thanks

**Comment by ri8ika** [comment]
For more information, I have defined the DB_PORT in heroku from setting and also in the application:
```
this.bind('datasources.config.db').to({
      name: 'postgres',
      connector: 'postgres',
      hostname: process.env.DB_HOST,
      port: process.env.DB_PORT,
      user: process.env.DB_USER,
      password: process.env.DB_PASSWORD,
      database: process.env.DB_DATABASE,
    });
    this.bind('datasources.db').toClass(PostgresDataSource);
```

**Comment by irineul** [comment]
Hi @raymondfeng I'm trying to build a development environment, following these instructions: https://loopback.io/doc/en/lb4/code-contrib-lb4.html#setting-up-development-environment

I'm receiving the same error when I try to do `npm run build`

> loopback-next@0.1.0 build /Users/irineul/Documents/personal-workspace/loopback/loopback-next
> node bin/run-lerna run build

> @loopback/example-context@1.2.14 build /Users/irineul/Documents/personal-workspace/loopback/loopback-next/examples/context
> lb-tsc
sh: lb-tsc: command not found

**Comment by raymondfeng** [comment]
Make sure you run `npm install` at the `loopback-next` directory first.

**Comment by irineul** [comment]
Hey, it's working now. For those who are having an error with build, maybe could help:
`sudo npm cache clear --force`
`npm run update-package-locks`
`npm ci` (again)
`npm run build`

**Comment by pranavatgithub** [comment]
still having issue while deploying in heroku

lb-tsc: not found

**Comment by afilp** [comment]
Me too, I cannot deploy on heroku, any ideas? Thanks!

2019-12-28T19:18:57.580830+00:00 app[web.1]: > lb-tsc
2019-12-28T19:18:57.580831+00:00 app[web.1]:
2019-12-28T19:18:57.599490+00:00 app[web.1]: sh: 1: lb-tsc: not found

**Comment by asaurav025** [comment]
@afilp @pranavatgithub Try deploying using the container. This is the only method which is currently working for heroku now.

**Comment by afilp** [comment]
@asaurav025 Thank you, can you please show us what you mean by "container"? You mean docker? Is there a page maybe with instructions for Heroku (or for just the container)?

Thanks again!

**Comment by afilp** [comment]
I think I have good news, I read somewhere to replace `web: slc run` with `web: node .` in `Procfile`, and it seems to be working in Heroku! I do see the `explorer` and can use all the endpoints.

@pranavatgithub @asaurav025 Can you please also verify this? Thanks.

**Comment by asaurav025** [comment]
@afilp Yes I meant docker. Here is the [link ](https://devcenter.heroku.com/articles/container-registry-and-runtime) which you can follow to know more.

**Comment by remicarette** [comment]
@afilp I have tried many solutions and it works when a create a Procfile : 
```web: node index.js```

and I also added a `heroku-postbuild` script in the package.json
```"heroku-postbuild": "npm run build"```

hope it helps.

**Comment by dacamposol** [comment]
> @asaurav025 Thank you, can you please show us what you mean by "container"? You mean docker? Is there a page maybe with instructions for Heroku (or for just the container)?
> 
> Thanks again!

Sorry for the delayed response, but in case that you're still wondering how to do that:

Create an **heroku.yml** file at the root folder of your project, the basic _Dockerfile_ shall be automatically created by the Loopback CLI, so just add the following text in that file:
```
build:
    docker:
        web: Dockerfile
```

Then, you will have to change the way that you're staging your app in Heroku, so perform the command **heroku stack:set container -a [YOUR_APP]** and perform the normal Git commands to deploy on Heroku:

1. `git add .`
2. `git commit -am "Deploying on Docker"`
3. `git push heroku master`

Then, your application will be deployed on a Node 10 container, so you'll be sure that the dependencies of TypeScript will be correctly installed.
