### ISSUE TITLE
How to let app insert id automatically?

### ISSUE THREAD

**Issue by ri8ika** [loopbackio/loopback.io#811]
In loopback 3, the id was inserted automatically. But in loopback 4, it is required even when creating models.

  ```
@property({
    type: 'string',
    id: true,
    required: true
  })
  id?: string;
```

After removing the required: true option worked when I was working with mongodb - the id was created automatically when post request happens. But for giving it a try to live on heroku, I needed to use postgres rather than mongodb. So, I decided to create  new project locally and using postgresql the preceeding way didn't work.

Meaning removing `required: true` doesn't work. Even having `required: false` doesn't work. 
```
500 error: null value in column "id" violates not-null constraint
```
Is there any way to have id not required when inserting data so that it can insert automatically?

PS: If I remove the id property the app will not work: `Property 'id' does not exist`. I hope there should be a way.

**Comment by dhmlau** [comment]
@ri8ika, IIRC, last time I got it to work for postgresql is:
```
  @property({
    type: 'string',
    id: true,
    generated: true,
  })
```

In case you're running issue with the postgresql setup, I've put together some information here: https://medium.com/loopback/loopback-4-todo-list-example-switching-to-a-sql-or-nosql-database-24cd68cf3647.

**Comment by ri8ika** [comment]
Ah, I tried it but still getting error:
```
500 error: null value in column "id" violates not-null constraint
```

**Comment by dhmlau** [comment]
@ri8ika , I just tried it out.  
```
@property({
    type: 'number',
    id: true,
    generated: true,
  })
  id: number;
```
Please note that the `id` variable (last line of the above snippet) is not optional.

**Comment by ri8ika** [comment]
Yes, I used generated option but it didn't work. Maybe the type is string in my case?
```
@property({
  type: 'string',
  id: true,
  generated: true,
})
id?: string;
```

**Comment by ri8ika** [comment]
Ah, I will try it.

**Comment by ri8ika** [comment]
Sorry, still not working for me. Maybe the type is string in my case?
```
@property({
    type: 'string',
    id: true,
    generated: true,
  })
  id: string;
```

**Comment by ri8ika** [comment]
I just tried using number, but still getting same error. Are you also using postgres?

**Comment by dhmlau** [comment]
Yes, I'm using postgres.  I assume you're not using the `automigrate` function to create the table? 
I just realized that if I use `npm run migrate` to get the table generated, it has some extra values in the property/column that we want to have id auto-gen. 
```
testdb=# \d customer
                               Table "public.customer"
  Column  |  Type   | Collation | Nullable |                 Default                  
----------+---------+-----------+----------+------------------------------------------
 custid   | integer |           | not null | nextval('customer_custid_seq'::regclass)
 custname | text    |           | not null | 
```
See the `nextval...`. 

I'm hitting a bug described in here: https://github.com/strongloop/loopback-next/issues/2398.  
Still investigating.

**Comment by dhmlau** [comment]
@ri8ika, I think I might know the key to get this to work.  I created the table on postgresql using `npm run migrate` command.  In that case, it adds the `nextval` in the column as mentioned [above](https://github.com/strongloop/loopback.io/issues/811#issuecomment-463745812).

I've tried it with column type being `integer` or `text` (on postgresql).  You can see my repo: 
https://github.com/dhmlau/loopback4-example-todo-customized (see `models\customer.model.ts` and the CustomerController to test). 

Assuming you created the table outside of LoopBack, did you set up the auto-increment for that column? I'm reading this.. http://www.postgresqltutorial.com/postgresql-serial/

**Comment by ri8ika** [comment]
Hmm, I had run the migration, but currently not seeing such `nextval`

**Comment by dhmlau** [comment]
did you run `npm run build` to make sure the latest code got transpiled? just in case..

**Comment by ri8ika** [comment]
Never. But why to run build? I'm testing it in development. Still no luck running after build.

**Comment by ri8ika** [comment]
I will try to figure out on this later. But I'm facing a major issue. Can you please help me on this?

https://github.com/strongloop/loopback.io/issues/813

The repo I have hosted in heroku is:

github.com/bhojport/nexserver

**Comment by dhmlau** [comment]
@ri8ika , i just had a chance to review your repo, and noticed that the id field is optional. https://github.com/bhojport/nexserver/blob/master/src/models/product.model.ts#L43-L48.  

It should be the following instead:
```
  @property({
    type: 'string',
    id: true,
    generated: true
  })
  id: string; <---- HERE
```

You can see my example [here](https://github.com/dhmlau/loopback4-example-todo-customized).

**Comment by ri8ika** [comment]
@dhmlau Yes, it's optional there. I have not updated the repo. But as per your suggestion, I already tried and didn't get it working - locally and so not updated in repo.

**Comment by dhmlau** [comment]
@ri8ika , I haven't got a chance to run your example.  But if it's the same as my example, try running `npm run clean` on your app and see if it helps.

**Comment by ri8ika** [comment]
Sorry, I can't migrate the db in heroku so stopped working on it.

**Comment by mwlalata** [comment]
loopback has the worst docs

**Comment by ctrevisan** [comment]
Just ran into a similar issue. As @dhmlau pointed out, the `generated` property needs to be set to `true`. However, _auto-updating_ (`npm run migrate`) doesn't seem to set the column to auto-increment; only _auto-migrating_ (`npm run migrate -- --rebuild`, which drops the tables and creates them again) seemed to work.

**Comment by emredmrl** [comment]
@ctrevisan thank you!!!

**Comment by kumawatajay215** [comment]
> 

This remove table data, this is not good solution if you do not want to loss data

**Comment by kumawatajay215** [comment]
@ctrevisan If you are using Postgres db then you can use query to set default value to primary
`CREATE SEQUENCE "table_id_seq"  
INCREMENT 1  
START 1;  
alter table public."table"
alter column id set default nextval('"table_id_seq"'::regclass)
`
