### ISSUE TITLE
Does Loopback 3 support MongoDb 4 transactions?

### ISSUE THREAD

**Issue by chi-tran** [loopbackio/loopback.io#814]
Mongo 4 supports transactions, has anyone got this working with loopback 3?

**Comment by dhmlau** [comment]
@chi-tran , sorry about the late reply.  Cross posting [my comment](https://github.com/strongloop/loopback-next/issues/1599):

> Talked to @bajtos @raymondfeng, what we should do regarding transaction support:
> - shorter term: explain to users how to open a transaction and pass the transaction token/handles around in options.
> - longer term: have a spike on a more elegant solution.

I've created a github issue for documenting how to open a transaction: https://github.com/strongloop/loopback-next/issues/2614. 

For the transaction support, please continue the discussion in https://github.com/strongloop/loopback-next/issues/1599. Thanks.
