### ISSUE TITLE
The HasManyThrough relations page is incomplete and misleading

### ISSUE THREAD

**Issue by rkamun1** [loopbackio/loopback.io#824]
## URL of the page 
https://loopback.io/doc/en/lb3/HasManyThrough-relations.html

## Nature of the issue 
The documentation is incomplete and misleading

## Expected behavior
The Has Many Through relationship has a joining Appointment model that is important and cannot be overlooked, unlike the join table in a HABTM relationship.

**Missing:**

- the has many relationship definition between the patient and appointments
- the has many relationship definition between the physician and appointments
- the new models added should be patient.appointments and physician.appointments which creates and appointment and JOINS the patient and the physician THROUGH that appointment.

## Actual behavior

- No join relationships defined
- patient.physicians and physician.patients are defined but are actually impossible methods.

## Suggested resolution

Documentation should include the importance of the join model appointments and highlight the methods that are added to physicians and patients

**Comment by dhmlau** [comment]
@SirBertly , would you be interested in helping us to improve the documentation?

**Comment by sirajalam049** [comment]
Well, yes, I really would, Loopback documentation needs many improvements.
