### ISSUE TITLE
How to convert lb2 app to lb3/4

### ISSUE THREAD

**Issue by sukeerthimogallapalli** [loopbackio/loopback.io#827]
Hi ,

i am new to loopback.i want to convert lb2 project to lb3/4 .For this do i need to re-implement the project ?or is there any auto-convertion way ? 

can u plz help me.

Thank you

**Comment by dhmlau** [comment]
@sukeerthi117, I'd like to point you to our recent blog post: https://strongloop.com/strongblog/lb3-extended-lts/.  I believe it covers the information you're looking for.

**Comment by dhmlau** [comment]
Closing it as resolved. @sukeerthi117, if you have further questions, please let ping me here so that i can reopen this issue or open a new issue.  Thanks.
