### ISSUE TITLE
[Proposal] Change main pages of loopback.io to use v4 pages

### ISSUE THREAD

**Issue by dhmlau** [loopbackio/loopback.io#839]
### Background
Currently we have 2 LoopBack web sites: loopback.io and v4.loopback.io. Our initial plan was to make the v4.loopback.io repo ready so that when we are ready (docs pages and everything are set up properly), we can make v4.loopback.io repo to serve at loopback.io.  

Since we are planning to keep most of the documentation infrastructure, it might be a good idea to make changes to the existing loopback.io main pages to have the LB4 content i.e.
- landing pages
- getting started
- resources
- etc. 

### Proposed changes
I'd like to propose that we:
- copy the pages from v4.loopback.io to loopback.io
- for the LB3 pages we still want to keep, it will be moved to loopback.io/lb3/

**Comment by nabdelgadir** [comment]
I like this proposal more than the other way around (suggested in https://github.com/strongloop/v4.loopback.io/issues/65), but if for any reason this way doesn't work we still have the other proposal.

If we do this switch, then should we add redirections for current lb3 pages like loopback.io/examples -> https://loopback.io/doc/en/lb4/Examples.html to not break existing urls? I don't think this is a big deal but just something to consider.

**Comment by dhmlau** [comment]
> If we do this switch, then should we add redirections for current lb3 pages like loopback.io/examples -> https://loopback.io/doc/en/lb4/Examples.html to not break existing urls? I don't think this is a big deal but just something to consider.

that's good point. Thanks for bringing this up.

**Comment by dhmlau** [comment]
Closing it as done. via PR https://github.com/strongloop/loopback.io/pull/840
