### ISSUE TITLE
ESLint links are broken

### ISSUE THREAD

**Issue by ktaletsk** [loopbackio/loopback.io#876]
## URL of the page 

https://loopback.io/doc/en/lb4/todo-tutorial-scaffolding.html

## Nature of the issue 

Links for ESLint are broken:
- https://palantir.github.io/eslint/usage/eslint-json/
- https://palantir.github.io/eslint/usage/eslint-json/

Source code line:
https://github.com/strongloop/loopback.io/blame/gh-pages/pages/en/lb4/tutorials/todo/todo-tutorial-scaffolding.md#L90

## Expected behavior

Should have a working link

## Actual behavior

Link to non-existing page (404). Looks like the related repo moved to maintenance mode: https://github.com/palantir/eslint-config-palantir.

## Suggested resolution

Use ESLint configuring link from: https://eslint.org/docs/user-guide/configuring

**Comment by dhmlau** [comment]
@ktaletsk , thanks for reporting this.  Would you like to submit a patch? Thanks.

**Comment by dhmlau** [comment]
Fixed via https://github.com/strongloop/loopback-next/pull/3864.  Closing this issue.
