### ISSUE TITLE
Links targeting to MD files broken

### ISSUE THREAD

**Issue by lokeshmohanty** [loopbackio/loopback.io#889]
## URL of the page 
https://loopback.io/doc/en/lb4/todo-tutorial-putting-it-together.html

## Nature of the issue 
Broken links

## Expected behavior
Links should target to html files

## Actual behavior
Links target to md files

**Comment by dhmlau** [comment]
@lokesh1197, thanks for catching this. I've commented on your PR, please see https://github.com/strongloop/loopback.io/pull/890#issuecomment-536107281.  Thanks!

**Comment by lokeshmohanty** [comment]
I have submitted a pull request here: https://github.com/strongloop/loopback-next/pull/3841
I will close the issue when it gets accepted
