### ISSUE TITLE
Set up and test PDF generation

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#89]
The original [Jekyll theme](https://github.com/tomjohnson1492/documentation-theme-jekyll) upon which the site is based provided for generating PDFs: http://idratherbewriting.com/documentation-theme-jekyll/mydoc_generating_pdfs.html.  

However, we haven't tried doing this yet, and because we've made a number of changes to the overall infrastructure we may need to make some changes to get PDF generation to work properly.

**Comment by anodynos** [comment]
Any chance you can generarte Loopback 3.0 docs as .pdf, as we have version 2?https://docs.strongloop.com/display/ALLDOCS/PDF+version

**Comment by crandmck** [comment]
Hi @anodynos I'll reopen this.  You are the first to ask for this...  If we can get a few +1's then we could justify spending some time on this.  Otherwise, it may be down to you.

In theory it shouldn't be hard, but we haven't gotten it working since the doc move to GitHub/Jekyll. If you're interested in pursuing it yourself, here are the general instructions: http://idratherbewriting.com/documentation-theme-jekyll/mydoc_generating_pdfs.html.  I moved all the scripts to https://github.com/strongloop/loopback.io/tree/gh-pages/scripts-pdf.  

A PR or other help is _always_ welcome!

**Comment by LeCoupa** [comment]
Would be really useful 👍
