### ISSUE TITLE
Define unique multiple column in model

### ISSUE THREAD

**Issue by aceraizel** [loopbackio/loopback.io#897]
How to define unique multiple column in model?
I'm using loopback 4.
Thank in advance!

**Comment by hevillalobosccxc** [comment]
Example
```
  @property({
    type: 'string',
    required: true,
    unique: true,
    index: true
  })
columnName: string;
``` 

@aceraizel

**Comment by dhmlau** [comment]
@aceraizel, i believe @hevillalobosccxc has answered your question. I'll close this issue. Thanks.
