### ISSUE TITLE
Broken anchor link

### ISSUE THREAD

**Issue by QuentinLB** [loopbackio/loopback.io#907]
## URL of the page 

https://loopback.io/doc/en/lb4/Model.html

## Nature of the issue 

In section Model Decorator > Supported Entries of Settings
Link to https://loopback.io/doc/en/lb4/Model.html#id-properties is broken because the anchor is missing from the page, content relative to id properties seems also missing from this page and nothing meaningful came out of a site wide search.

## Expected behavior

I except to be taken to a page section with relevent informations on id properties (I'm looking for a way to have generated int id eg : 0,1,2...)

## Actual behavior

When I click the link nothing happens 

## Suggested resolution

By providing the related information and setting up the missing anchor.

## Acceptance Criteria
_I'm not sure what's the id-properties anchor was supposed to point to but I didn't see anything matching_

- [ ] Make sure https://loopback.io/doc/en/lb4/Model.html#id-properties is not "broken" 
   - [ ] Add a `id properties` section that corresponds to the content in LB3: https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html#id-properties

**Comment by dhmlau** [comment]
@QuentinLB, thanks for reporting this issue. I wonder if the anchor meant to point to content something like in https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html#id-properties.  Would you like to submit a PR for that? The corresponding docs page is https://github.com/strongloop/loopback-next/blob/master/docs/site/Model.md.

For your question about generated id, you can use the `generated: true` settings. Make sure that the id field is not an optional variable.
```
@property({
    type: 'string',
    id: true,
    generated: true,
  })
  custid: string;
```
For example, see https://github.com/dhmlau/loopback4-example-todo-customized#how-to-auto-generate-the-ids

**Comment by QuentinLB** [comment]
Hey @dhmlau, thanks for your answer. Sorry for the PR but I don't want to sign the CLA, I hope you understand.

**Comment by QuentinLB** [comment]
Feel free to grab the referenced commit though.

**Comment by dhmlau** [comment]
No problem @QuentinLB, I understand.  We're planning to switch the contribution method from CLA to DCO (https://github.com/probot/dco) in a near future.  Do you think you would be able to contribute in the future with DCO in place?

**Comment by dhmlau** [comment]
I'd like to keep this issue open because that's something should be fixed.

**Comment by QuentinLB** [comment]
I understand that it may be important for your org & legal team but I don't want to have this discussion with my legal department and explain them open source and contributions. Sorry.

**Comment by agnes512** [comment]
Maybe we can find something to check if we have any dangling links
