### ISSUE TITLE
i have Windows10 .and npm version 3.10.6 . when i am installing  npm install -g strongloop. giving  error  . the error is 

### ISSUE THREAD

**Issue by raviranjan290620** [loopbackio/loopback.io#93]
## URL of the page

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\HP\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "node-pre-gyp"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.6
npm ERR! path C:\Users\HP\AppData\Roaming\npm\node_modules.staging\sqlite3-246ee2c4
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rmdir

npm ERR! EBUSY: resource busy or locked, rmdir 'C:\Users\HP\AppData\Roaming\npm\node_modules.staging\sqlite3-246ee2c4'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\HP\AppData\Roaming\npm\node_modules.staging\sqlite3-246ee2c4\npm-debug.log
npm WARN install:sqlite3@3.1.5 sqlite3@3.1.5 preinstall: `npm install node-pre-gyp`
npm WARN install:sqlite3@3.1.5 Exit status 4294963214

> strong-arc@1.8.8 preinstall C:\Users\HP\AppData\Roaming\npm\node_modules.staging\strong-arc-13fb10de
> node .sl-blip.js

C:\Users\HP\AppData\Roaming\npm
`-- (empty)

npm WARN optional Skipping failed optional dependency /strongloop/modern-syslog:
npm WARN notsup Not compatible with your operating system or architecture: modern-syslog@1.1.4
npm WARN optional Skipping failed optional dependency /strongloop/strong-supervisor/modern-syslog:
npm WARN notsup Not compatible with your operating system or architecture: modern-syslog@1.1.4
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\HP\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "-g" "strongloop"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.6
npm ERR! file C:\WINDOWS\system32\cmd.exe
npm ERR! path C:\WINDOWS\system32\cmd.exe
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\WINDOWS\system32\cmd.exe

npm ERR! strong-arc@1.8.8 preinstall: `node .sl-blip.js`
npm ERR! spawn C:\WINDOWS\system32\cmd.exe ENOENT
npm ERR!
npm ERR! Failed at the strong-arc@1.8.8 preinstall script 'node .sl-blip.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the strong-arc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node .sl-blip.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs strong-arc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls strong-arc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\Angular-2\Angular-2 firebase\Demoapp2\src\app\npm-debug.log
If applicable.
## Nature of the issue

Is this an issue with the layout/behavior/UX of the site or a problem with missing/inaccurate documentation content?
In general, use this (loopback.io) repo for issues with layout/behavior/UX of the site, and other repos for doc content.
## Expected behavior

What did you expect to happen?
## Actual behavior

What actually happenend, with steps to reproduce (if applicable).
## Suggested resolution

How do you think this should be resolved (optional).

**Comment by crandmck** [comment]
This repo is for issues related to the documentation.  

Please open your issue in the loopback repo: https://github.com/strongloop/loopback/issues.
