### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ryan-senn** [loopbackio/loopback.io#962]
## URL of the page 

https://loopback.io/doc/index.html

## Nature of the issue 

The tag "getting started" at the bottom of the page links to https://loopback.io/doc/tag_getting_started.html, which shows me a 404 not found.

### Acceptance Criteria (Updated by the LoopBack team)
- [ ] remove the broken link in the page.

_For longer term solution, we might want to think about re-introducing tags in the LB4 docs_

**Comment by dhmlau** [comment]
@ryan-senn, thanks for reporting this. 
Ideally, this would point to LB4 docs with `getting_started` tag.  But it seems like the LB4 docs are not using the `tag` field in the front matter. 

As the quick fix, I think we can remove the broken link in the page. 
For longer term solution, we might want to think about re-introducing tags in the LB4 docs.

**Comment by dhmlau** [comment]
Discussion from today's estimation meeting: 
- we'll remove the broken link as a shorter term solution
- for longer term solution, it might be a good idea to use tags for discovery of the content.
