### ISSUE TITLE
Getting Started | Unable to 'git checkout step1'

### ISSUE THREAD

**Issue by plug-n-play** [loopbackio/loopback.io#97]
## Expected behavior

Executing 'git checkout step1' should work
## Actual behavior

Get following error:
"error: pathspec 'step1' did not match any file(s) known to git."
## Suggested resolution

This should work as expected instead of giving an error

**Comment by crandmck** [comment]
@superkhau As I mentioned you need to replace the tagged releases https://github.com/strongloop/loopback-getting-started/releases

**Comment by crandmck** [comment]
@plug-n-play The releases are now back in the repo, so you should be able to check out the various steps as instructed by the docs.  Sorry for the inconvenience.
